name: mexy_rider
description: "App de riders Mexy."
publish_to: 'none'
version: 1.0.2+3

environment:
  sdk: ^3.13.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_foreground_task: ^9.1.0
  geolocator: ^14.0.0
  google_sign_in: ^6.2.2
  http: ^1.5.0
  supabase_flutter: ^2.9.0
  google_maps_flutter: ^2.12.3
  google_maps_flutter_android: ^2.19.12
  google_maps_flutter_platform_interface: ^2.16.0
  smooth_sheets: ^1.1.1
  url_launcher: ^6.3.2
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/bells.wav
