import type { MenuQrCornerStyle, MenuQrDotStyle, MenuQrPreset } from './menuQrStudio';

type PresetSeed = {
  id: string;
  label: string;
  theme: string;
  dot: string;
  bg: string;
  corner?: string;
  cornerDot?: string;
  dotStyle?: MenuQrDotStyle;
  cornerStyle?: MenuQrCornerStyle;
  cornerDotStyle?: MenuQrCornerStyle;
  transparent?: boolean;
};

function qrPreset(seed: PresetSeed): MenuQrPreset {
  return {
    id: seed.id,
    label: seed.label,
    theme: seed.theme,
    config: {
      dotColor: seed.dot,
      cornerColor: seed.corner ?? seed.dot,
      cornerDotColor: seed.cornerDot ?? seed.corner ?? seed.dot,
      backgroundColor: seed.bg,
      transparentBackground: seed.transparent ?? false,
      dotStyle: seed.dotStyle ?? 'rounded',
      cornerStyle: seed.cornerStyle ?? 'extra-rounded',
      cornerDotStyle: seed.cornerDotStyle ?? 'dot',
    },
  };
}

/** Temas QR escaneables — paletas alineadas con catálogo de menú + ui-ux-pro-max. */
export const MENU_QR_PRESET_CATALOG: MenuQrPreset[] = [
  // —— Esenciales ——
  qrPreset({
    id: 'classic',
    label: 'Clásico',
    theme: 'Alto contraste scan-safe',
    dot: '#020617',
    bg: '#ffffff',
    dotStyle: 'square',
    cornerStyle: 'square',
    cornerDotStyle: 'square',
  }),
  qrPreset({
    id: 'rounded',
    label: 'Redondeado',
    theme: 'Minimal default',
    dot: '#0f172a',
    bg: '#ffffff',
  }),
  qrPreset({
    id: 'slate',
    label: 'Slate neutro',
    theme: 'Original / dashboard',
    dot: '#111827',
    bg: '#f8fafc',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'verde-original',
    label: 'Verde delivery',
    theme: 'Original Verde accent',
    dot: '#14532d',
    corner: '#166534',
    cornerDot: '#06c167',
    bg: '#f0fdf4',
    dotStyle: 'dots',
  }),

  // —— Mexicano & casual ——
  qrPreset({
    id: 'taqueria',
    label: 'Taquería',
    theme: 'Taquería Viva',
    dot: '#450a0a',
    corner: '#dc2626',
    cornerDot: '#ca8a04',
    bg: '#fef2f2',
  }),
  qrPreset({
    id: 'clasico-rojo',
    label: 'Clásico rojo',
    theme: 'Clásico Rojo menú',
    dot: '#450a0a',
    corner: '#dc2626',
    cornerDot: '#ca8a04',
    bg: '#fef2f2',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'antojo-urbano',
    label: 'Antojo urbano',
    theme: 'Antojo Urbano / street',
    dot: '#431407',
    corner: '#ea580c',
    cornerDot: '#fbbf24',
    bg: '#fff7ed',
    dotStyle: 'square',
    cornerStyle: 'dot',
  }),
  qrPreset({
    id: 'tex-mex',
    label: 'Tex-Mex',
    theme: 'Tex-Mex Cantina',
    dot: '#7f1d1d',
    corner: '#dc2626',
    cornerDot: '#2563eb',
    bg: '#fff1f2',
    dotStyle: 'extra-rounded',
  }),
  qrPreset({
    id: 'mexicano-patrio',
    label: 'Patrio MX',
    theme: 'Festividades México',
    dot: '#14532d',
    corner: '#166534',
    cornerDot: '#b91c1c',
    bg: '#fefce8',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'cinco-mayo',
    label: 'Cinco de Mayo',
    theme: 'Cinco de Mayo festivo',
    dot: '#14532d',
    corner: '#15803d',
    cornerDot: '#dc2626',
    bg: '#fef9c3',
    dotStyle: 'rounded',
  }),
  qrPreset({
    id: 'dia-muertos',
    label: 'Día de Muertos',
    theme: 'Día de Muertos',
    dot: '#faf5ff',
    corner: '#f97316',
    cornerDot: '#fbbf24',
    bg: '#1e1b4b',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'navidad',
    label: 'Navidad',
    theme: 'Navidad Posadas',
    dot: '#7f1d1d',
    corner: '#b91c1c',
    cornerDot: '#15803d',
    bg: '#fef2f2',
    dotStyle: 'classy',
  }),

  // —— Premium & fine dining ——
  qrPreset({
    id: 'premium-oro',
    label: 'Premium oro',
    theme: 'Fine Dining Oro / Luxury',
    dot: '#0c0a09',
    corner: '#1c1917',
    cornerDot: '#ca8a04',
    bg: '#fafaf9',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'maitre',
    label: 'Maître',
    theme: 'Maître Élégance',
    dot: '#0c0a09',
    corner: '#44403c',
    cornerDot: '#ca8a04',
    bg: '#fafaf9',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'steakhouse',
    label: 'Steakhouse',
    theme: 'Steak Carbon',
    dot: '#fafaf9',
    corner: '#e7e5e4',
    cornerDot: '#ca8a04',
    bg: '#0c0a09',
    dotStyle: 'square',
    cornerStyle: 'square',
    cornerDotStyle: 'square',
  }),
  qrPreset({
    id: 'cava-vino',
    label: 'Cava y vino',
    theme: 'Cava y Vino',
    dot: '#3b0764',
    corner: '#581c87',
    cornerDot: '#ca8a04',
    bg: '#faf5ff',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'bistro-frances',
    label: 'Bistro francés',
    theme: 'Bistro Francés',
    dot: '#1e3a8a',
    corner: '#1d4ed8',
    cornerDot: '#ca8a04',
    bg: '#eff6ff',
    dotStyle: 'classy-rounded',
  }),

  // —— Café & panadería ——
  qrPreset({
    id: 'cafe',
    label: 'Café',
    theme: 'Coffee Shop / Café Artesanal',
    dot: '#451a03',
    corner: '#78350f',
    cornerDot: '#92400e',
    bg: '#fef3c7',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'roastery',
    label: 'Roastery',
    theme: 'Roastery Latte',
    dot: '#451a03',
    corner: '#b5651d',
    cornerDot: '#6b7b3c',
    bg: '#f5f0e1',
    dotStyle: 'rounded',
  }),
  qrPreset({
    id: 'pasteleria',
    label: 'Pastelería',
    theme: 'Pastelería Dulce',
    dot: '#831843',
    corner: '#db2777',
    cornerDot: '#f472b6',
    bg: '#fff7ed',
    dotStyle: 'extra-rounded',
  }),
  qrPreset({
    id: 'brunch',
    label: 'Brunch',
    theme: 'Brunch Dorado',
    dot: '#78350f',
    corner: '#b45309',
    cornerDot: '#ca8a04',
    bg: '#fffbeb',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'helado',
    label: 'Heladería',
    theme: 'Helado Gelato',
    dot: '#0e7490',
    corner: '#06b6d4',
    cornerDot: '#f472b6',
    bg: '#ecfeff',
    dotStyle: 'extra-rounded',
  }),
  qrPreset({
    id: 'bakery-cream',
    label: 'Panadería crema',
    theme: 'Bakery/Cafe ui-ux-pro-max',
    dot: '#78350f',
    corner: '#92400e',
    cornerDot: '#b45309',
    bg: '#fef3c7',
    dotStyle: 'classy-rounded',
  }),

  // —— Italiano & pizza ——
  qrPreset({
    id: 'trattoria',
    label: 'Trattoria',
    theme: 'Trattoria Roma',
    dot: '#831843',
    corner: '#db2777',
    cornerDot: '#9d174d',
    bg: '#fdf2f8',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'pizzeria',
    label: 'Pizzería',
    theme: 'Pizzería Napoli',
    dot: '#7f1d1d',
    corner: '#dc2626',
    cornerDot: '#15803d',
    bg: '#fff7ed',
    dotStyle: 'rounded',
  }),

  // —— Asiático ——
  qrPreset({
    id: 'sushi-zen',
    label: 'Sushi Zen',
    theme: 'Sushi Zen minimal',
    dot: '#171717',
    corner: '#262626',
    cornerDot: '#525252',
    bg: '#ffffff',
    dotStyle: 'square',
    cornerStyle: 'square',
  }),
  qrPreset({
    id: 'ramen',
    label: 'Ramen',
    theme: 'Ramen Miso',
    dot: '#431407',
    corner: '#9a3412',
    cornerDot: '#c2410c',
    bg: '#fff7ed',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'k-bbq',
    label: 'K-BBQ',
    theme: 'Korean BBQ',
    dot: '#1f2937',
    corner: '#cd2e3a',
    cornerDot: '#0047a0',
    bg: '#fff8f6',
    dotStyle: 'square',
    cornerStyle: 'dot',
  }),
  qrPreset({
    id: 'thai',
    label: 'Thai',
    theme: 'Thai Vibrante',
    dot: '#7c2d12',
    corner: '#ea580c',
    cornerDot: '#15803d',
    bg: '#fff7ed',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'dim-sum',
    label: 'Dim Sum',
    theme: 'Dim Sum China',
    dot: '#7f1d1d',
    corner: '#b91c1c',
    cornerDot: '#ca8a04',
    bg: '#fef2f2',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'pho',
    label: 'Pho',
    theme: 'Pho Saigón',
    dot: '#14532d',
    corner: '#166534',
    cornerDot: '#ca8a04',
    bg: '#f0fdf4',
    dotStyle: 'rounded',
  }),
  qrPreset({
    id: 'poke',
    label: 'Poke',
    theme: 'Poke Hawaiian',
    dot: '#0c4a6e',
    corner: '#0284c7',
    cornerDot: '#f97316',
    bg: '#f0f9ff',
    dotStyle: 'extra-rounded',
  }),
  qrPreset({
    id: 'void-omakase',
    label: 'Omakase noir',
    theme: 'Void Omakase dark',
    dot: '#fafafa',
    corner: '#d4d4d4',
    cornerDot: '#ca8a04',
    bg: '#0a0a0a',
    dotStyle: 'square',
    cornerStyle: 'square',
  }),

  // —— Americano & fast food ——
  qrPreset({
    id: 'burger',
    label: 'Burger',
    theme: 'Burger Bold',
    dot: '#450a0a',
    corner: '#dc2626',
    cornerDot: '#1e3a8a',
    bg: '#fef2f2',
    dotStyle: 'square',
    cornerStyle: 'dot',
  }),
  qrPreset({
    id: 'food-truck',
    label: 'Food truck',
    theme: 'Food Truck',
    dot: '#1c1917',
    corner: '#fbbf24',
    cornerDot: '#ef4444',
    bg: '#fffbeb',
    dotStyle: 'square',
  }),
  qrPreset({
    id: 'diner',
    label: 'Diner retro',
    theme: 'Diner Retro',
    dot: '#1e3a8a',
    corner: '#dc2626',
    cornerDot: '#fbbf24',
    bg: '#eff6ff',
    dotStyle: 'square',
    cornerStyle: 'square',
  }),
  qrPreset({
    id: 'bbq-humo',
    label: 'BBQ humo',
    theme: 'BBQ Humo smokehouse',
    dot: '#431407',
    corner: '#7c2d12',
    cornerDot: '#a16207',
    bg: '#fff7ed',
    dotStyle: 'dots',
  }),

  // —— Saludable & orgánico ——
  qrPreset({
    id: 'ensalada',
    label: 'Ensalada fresca',
    theme: 'Ensalada Fresca / bowls',
    dot: '#164e63',
    corner: '#0891b2',
    cornerDot: '#15803d',
    bg: '#ecfeff',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'vegan',
    label: 'Vegan verde',
    theme: 'Vegan Verde',
    dot: '#14532d',
    corner: '#166534',
    cornerDot: '#65a30d',
    bg: '#f7fee7',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'granja',
    label: 'Granja orgánica',
    theme: 'Granja Orgánica',
    dot: '#365314',
    corner: '#4d7c0f',
    cornerDot: '#854d0e',
    bg: '#f7fee7',
    dotStyle: 'rounded',
  }),

  // —— Mar & costa ——
  qrPreset({
    id: 'mariscos',
    label: 'Mariscos',
    theme: 'Mariscos Costa',
    dot: '#0c4a6e',
    corner: '#0369a1',
    cornerDot: '#0ea5e9',
    bg: '#f0f9ff',
  }),
  qrPreset({
    id: 'ceviche',
    label: 'Ceviche',
    theme: 'Ceviche Perú',
    dot: '#0c4a6e',
    corner: '#0284c7',
    cornerDot: '#f97316',
    bg: '#f0f9ff',
    dotStyle: 'extra-rounded',
  }),
  qrPreset({
    id: 'abisal',
    label: 'Abisal mar',
    theme: 'Abisal Mar dark',
    dot: '#e0f2fe',
    corner: '#38bdf8',
    cornerDot: '#22d3ee',
    bg: '#020617',
    dotStyle: 'dots',
  }),

  // —— Mundial & fusión ——
  qrPreset({
    id: 'curry',
    label: 'Curry India',
    theme: 'Curry India',
    dot: '#7c2d12',
    corner: '#c2410c',
    cornerDot: '#ca8a04',
    bg: '#fff7ed',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'mediterraneo',
    label: 'Mediterráneo',
    theme: 'Mediterráneo',
    dot: '#1e3a8a',
    corner: '#2563eb',
    cornerDot: '#ca8a04',
    bg: '#eff6ff',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'griego',
    label: 'Griego',
    theme: 'Griego Egeo',
    dot: '#1e3a8a',
    corner: '#2563eb',
    cornerDot: '#0ea5e9',
    bg: '#f0f9ff',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'libanes',
    label: 'Libanés',
    theme: 'Libanés Fénix',
    dot: '#7c2d12',
    corner: '#c2410c',
    cornerDot: '#ca8a04',
    bg: '#fff7ed',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'cubano',
    label: 'Cubano',
    theme: 'Cubano Caribe',
    dot: '#831843',
    corner: '#db2777',
    cornerDot: '#0ea5e9',
    bg: '#fdf2f8',
    dotStyle: 'rounded',
  }),

  // —— Modo oscuro / nightlife ——
  qrPreset({
    id: 'noir',
    label: 'Noir',
    theme: 'OLED dark sticker',
    dot: '#fafafa',
    corner: '#f8fafc',
    cornerDot: '#e2e8f0',
    bg: '#0a0a0a',
    dotStyle: 'square',
    cornerStyle: 'square',
    cornerDotStyle: 'square',
  }),
  qrPreset({
    id: 'street-neon',
    label: 'Street neon',
    theme: 'Street Neon / cyber',
    dot: '#f8fafc',
    corner: '#e11d48',
    cornerDot: '#fbbf24',
    bg: '#0f172a',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'neon-tokyo',
    label: 'Neon Tokyo',
    theme: 'Neon Tokyo',
    dot: '#f0f9ff',
    corner: '#e11d48',
    cornerDot: '#a855f7',
    bg: '#020617',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'lounge',
    label: 'Lounge',
    theme: 'Lounge Nocturno',
    dot: '#fafaf9',
    corner: '#d6d3d1',
    cornerDot: '#ca8a04',
    bg: '#1c1917',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'obsidiana',
    label: 'Obsidiana oro',
    theme: 'Obsidiana Oro',
    dot: '#fafaf9',
    corner: '#ca8a04',
    cornerDot: '#eab308',
    bg: '#0c0a09',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'carbon-bbq',
    label: 'Carbon BBQ',
    theme: 'Carbon BBQ dark',
    dot: '#fef3c7',
    corner: '#f97316',
    cornerDot: '#ef4444',
    bg: '#0c0a09',
    dotStyle: 'square',
  }),
  qrPreset({
    id: 'midnight-taco',
    label: 'Midnight taco',
    theme: 'Midnight Taco',
    dot: '#fef08a',
    corner: '#e11d48',
    cornerDot: '#22c55e',
    bg: '#0f172a',
    dotStyle: 'rounded',
  }),

  // —— SaaS / modernos ——
  qrPreset({
    id: 'marino',
    label: 'Marino',
    theme: 'Navy high contrast',
    dot: '#020617',
    corner: '#0f172a',
    cornerDot: '#0369a1',
    bg: '#f8fafc',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'indigo',
    label: 'Índigo',
    theme: 'Design System SaaS',
    dot: '#312e81',
    corner: '#4f46e5',
    cornerDot: '#6366f1',
    bg: '#eef2ff',
  }),
  qrPreset({
    id: 'verde-delivery',
    label: 'Verde app',
    theme: 'Delivery organic',
    dot: '#14532d',
    corner: '#166534',
    cornerDot: '#15803d',
    bg: '#f0fdf4',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'coral',
    label: 'Coral vivo',
    theme: 'Vibrant consumer',
    dot: '#9f1239',
    corner: '#e11d48',
    cornerDot: '#f97316',
    bg: '#fff1f2',
    dotStyle: 'extra-rounded',
  }),
  qrPreset({
    id: 'lavanda',
    label: 'Lavanda',
    theme: 'Soft wellness',
    dot: '#4c1d95',
    corner: '#6d28d9',
    cornerDot: '#8b5cf6',
    bg: '#f5f3ff',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'tierra',
    label: 'Tierra',
    theme: 'Nature Distilled',
    dot: '#44403c',
    corner: '#78716c',
    cornerDot: '#b5651d',
    bg: '#f5f0e1',
    dotStyle: 'classy-rounded',
  }),

  // —— Festividades MX (más) ——
  qrPreset({
    id: 'grito',
    label: 'Grito MX',
    theme: 'Grito Independencia',
    dot: '#14532d',
    corner: '#166534',
    cornerDot: '#b91c1c',
    bg: '#fefce8',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'septiembre',
    label: 'Septiembre',
    theme: 'Septiembre Patrio',
    dot: '#14532d',
    corner: '#15803d',
    cornerDot: '#dc2626',
    bg: '#f0fdf4',
    dotStyle: 'rounded',
  }),
  qrPreset({
    id: 'revolucion',
    label: 'Revolución',
    theme: 'Revolución MX',
    dot: '#7f1d1d',
    corner: '#b91c1c',
    cornerDot: '#1e3a8a',
    bg: '#fef2f2',
    dotStyle: 'square',
    cornerStyle: 'square',
  }),
  qrPreset({
    id: 'mundial-2026',
    label: 'Mundial 2026',
    theme: 'Mundial FIFA 2026',
    dot: '#14532d',
    corner: '#166534',
    cornerDot: '#ca8a04',
    bg: '#f0fdf4',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'posadas',
    label: 'Posadas',
    theme: 'Navidad Posadas festivo',
    dot: '#7f1d1d',
    corner: '#dc2626',
    cornerDot: '#15803d',
    bg: '#fffbeb',
    dotStyle: 'extra-rounded',
  }),
  qrPreset({
    id: 'ofrenda',
    label: 'Ofrenda',
    theme: 'Día de Muertos cempasúchil',
    dot: '#faf5ff',
    corner: '#f97316',
    cornerDot: '#eab308',
    bg: '#312e81',
    dotStyle: 'dots',
  }),

  // —— Modo oscuro (más) ——
  qrPreset({
    id: 'noir-copa',
    label: 'Noir copa',
    theme: 'Noir Copa cocktail bar',
    dot: '#fafaf9',
    corner: '#d6d3d1',
    cornerDot: '#a8a29e',
    bg: '#0c0a09',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'cyber-void',
    label: 'Cyber void',
    theme: 'Cyber Void neon',
    dot: '#f0f9ff',
    corner: '#22d3ee',
    cornerDot: '#a855f7',
    bg: '#020617',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'lampara-ramen',
    label: 'Lámpara ramen',
    theme: 'Lámpara Ramen izakaya',
    dot: '#fef3c7',
    corner: '#fbbf24',
    cornerDot: '#dc2626',
    bg: '#1c1917',
    dotStyle: 'rounded',
  }),
  qrPreset({
    id: 'forno-notte',
    label: 'Forno notte',
    theme: 'Forno Notte pizzería dark',
    dot: '#fef2f2',
    corner: '#fca5a5',
    cornerDot: '#f97316',
    bg: '#0c0a09',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'speakeasy',
    label: 'Speakeasy',
    theme: 'Bar oculto art déco',
    dot: '#fef3c7',
    corner: '#ca8a04',
    cornerDot: '#78716c',
    bg: '#1c1917',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'vinyl-bar',
    label: 'Vinyl bar',
    theme: 'Bar retro vinilo',
    dot: '#fafaf9',
    corner: '#f97316',
    cornerDot: '#0ea5e9',
    bg: '#171717',
    dotStyle: 'square',
    cornerStyle: 'dot',
  }),

  // —— Cocinas & venue (más) ——
  qrPreset({
    id: 'original-menu',
    label: 'Menú original',
    theme: 'Original menú Venddelo',
    dot: '#111827',
    corner: '#1f2937',
    cornerDot: '#06c167',
    bg: '#f8fafc',
    dotStyle: 'rounded',
  }),
  qrPreset({
    id: 'tapas-bar',
    label: 'Tapas bar',
    theme: 'Tapas españolas',
    dot: '#7f1d1d',
    corner: '#b91c1c',
    cornerDot: '#ca8a04',
    bg: '#fff7ed',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'cantina-agave',
    label: 'Cantina agave',
    theme: 'Cantina mezcal & tequila',
    dot: '#14532d',
    corner: '#166534',
    cornerDot: '#ca8a04',
    bg: '#f0fdf4',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'marisqueria',
    label: 'Marisquería',
    theme: 'Marisquería playa',
    dot: '#0c4a6e',
    corner: '#0369a1',
    cornerDot: '#f97316',
    bg: '#ecfeff',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'sushi-bar',
    label: 'Sushi bar',
    theme: 'Sushi bar rojo',
    dot: '#450a0a',
    corner: '#dc2626',
    cornerDot: '#171717',
    bg: '#fafafa',
    dotStyle: 'square',
    cornerStyle: 'square',
  }),
  qrPreset({
    id: 'wok-flame',
    label: 'Wok flame',
    theme: 'Wok asiático fuego',
    dot: '#7f1d1d',
    corner: '#dc2626',
    cornerDot: '#ca8a04',
    bg: '#fff1f2',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'tandoor',
    label: 'Tandoor',
    theme: 'Tandoor indio',
    dot: '#7c2d12',
    corner: '#ea580c',
    cornerDot: '#ca8a04',
    bg: '#fff7ed',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'falafel',
    label: 'Falafel',
    theme: 'Street food mediterráneo',
    dot: '#365314',
    corner: '#65a30d',
    cornerDot: '#ca8a04',
    bg: '#f7fee7',
    dotStyle: 'rounded',
  }),
  qrPreset({
    id: 'creperia',
    label: 'Crêpería',
    theme: 'Crêpería bretona',
    dot: '#1e3a8a',
    corner: '#2563eb',
    cornerDot: '#ca8a04',
    bg: '#eff6ff',
    dotStyle: 'extra-rounded',
  }),
  qrPreset({
    id: 'churreria',
    label: 'Churrería',
    theme: 'Churrería chocolate',
    dot: '#78350f',
    corner: '#92400e',
    cornerDot: '#b45309',
    bg: '#fef3c7',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'jugos-smoothie',
    label: 'Jugos',
    theme: 'Jugos & smoothies',
    dot: '#be185d',
    corner: '#db2777',
    cornerDot: '#65a30d',
    bg: '#fdf2f8',
    dotStyle: 'extra-rounded',
  }),
  qrPreset({
    id: 'poke-bowl',
    label: 'Poke bowl',
    theme: 'Poke bowl tropical',
    dot: '#0c4a6e',
    corner: '#06b6d4',
    cornerDot: '#f97316',
    bg: '#ecfeff',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'hot-pot',
    label: 'Hot pot',
    theme: 'Hot pot chino',
    dot: '#7f1d1d',
    corner: '#b91c1c',
    cornerDot: '#ca8a04',
    bg: '#fef2f2',
    dotStyle: 'rounded',
  }),
  qrPreset({
    id: 'arepa',
    label: 'Arepa',
    theme: 'Arepa venezolana',
    dot: '#78350f',
    corner: '#b45309',
    cornerDot: '#ca8a04',
    bg: '#fffbeb',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'empanadas',
    label: 'Empanadas',
    theme: 'Empanadas argentinas',
    dot: '#1e3a8a',
    corner: '#2563eb',
    cornerDot: '#fbbf24',
    bg: '#eff6ff',
    dotStyle: 'rounded',
  }),

  // —— Premium & boutique (más) ——
  qrPreset({
    id: 'champagne',
    label: 'Champagne',
    theme: 'Champagne brunch luxury',
    dot: '#0c0a09',
    corner: '#44403c',
    cornerDot: '#ca8a04',
    bg: '#fafaf9',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'sommelier',
    label: 'Sommelier',
    theme: 'Wine cellar premium',
    dot: '#3b0764',
    corner: '#6b21a8',
    cornerDot: '#ca8a04',
    bg: '#faf5ff',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'chef-table',
    label: 'Chef table',
    theme: 'Chef table experiencia',
    dot: '#fafaf9',
    corner: '#d6d3d1',
    cornerDot: '#ca8a04',
    bg: '#1c1917',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'rooftop',
    label: 'Rooftop',
    theme: 'Rooftop sunset lounge',
    dot: '#431407',
    corner: '#ea580c',
    cornerDot: '#7c3aed',
    bg: '#fff7ed',
    dotStyle: 'dots',
  }),

  // —— Casual & delivery (más) ——
  qrPreset({
    id: 'wings',
    label: 'Wings',
    theme: 'Wings & sports bar',
    dot: '#7f1d1d',
    corner: '#dc2626',
    cornerDot: '#1e3a8a',
    bg: '#fef2f2',
    dotStyle: 'square',
    cornerStyle: 'dot',
  }),
  qrPreset({
    id: 'pasta-box',
    label: 'Pasta box',
    theme: 'Pasta delivery',
    dot: '#7f1d1d',
    corner: '#dc2626',
    cornerDot: '#15803d',
    bg: '#fff7ed',
    dotStyle: 'rounded',
  }),
  qrPreset({
    id: 'bowl-healthy',
    label: 'Bowl healthy',
    theme: 'Bowls saludables',
    dot: '#14532d',
    corner: '#16a34a',
    cornerDot: '#f97316',
    bg: '#f0fdf4',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'cloud-kitchen',
    label: 'Cloud kitchen',
    theme: 'Dark kitchen delivery',
    dot: '#0f172a',
    corner: '#334155',
    cornerDot: '#06c167',
    bg: '#f8fafc',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'late-night',
    label: 'Late night',
    theme: 'Late night snacks',
    dot: '#fef08a',
    corner: '#fbbf24',
    cornerDot: '#e11d48',
    bg: '#0f172a',
    dotStyle: 'rounded',
  }),

  // —— Paletas modernas (más) ——
  qrPreset({
    id: 'mint-fresh',
    label: 'Menta fresh',
    theme: 'Mint wellness modern',
    dot: '#134e4a',
    corner: '#0d9488',
    cornerDot: '#14b8a6',
    bg: '#f0fdfa',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'sunset',
    label: 'Sunset',
    theme: 'Sunset gradient vibe',
    dot: '#9f1239',
    corner: '#e11d48',
    cornerDot: '#f97316',
    bg: '#fff1f2',
    dotStyle: 'extra-rounded',
  }),
  qrPreset({
    id: 'ocean-deep',
    label: 'Océano',
    theme: 'Ocean deep blue',
    dot: '#0c4a6e',
    corner: '#075985',
    cornerDot: '#38bdf8',
    bg: '#f0f9ff',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'sand-beige',
    label: 'Arena',
    theme: 'Sand beach neutral',
    dot: '#44403c',
    corner: '#78716c',
    cornerDot: '#0ea5e9',
    bg: '#fafaf9',
    dotStyle: 'rounded',
  }),
  qrPreset({
    id: 'berry',
    label: 'Berry',
    theme: 'Berry dessert pink',
    dot: '#831843',
    corner: '#be185d',
    cornerDot: '#db2777',
    bg: '#fdf2f8',
    dotStyle: 'extra-rounded',
  }),
  qrPreset({
    id: 'espresso',
    label: 'Espresso',
    theme: 'Espresso bar dark roast',
    dot: '#fafaf9',
    corner: '#d6d3d1',
    cornerDot: '#92400e',
    bg: '#292524',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'matcha',
    label: 'Matcha',
    theme: 'Matcha tea house',
    dot: '#365314',
    corner: '#4d7c0f',
    cornerDot: '#65a30d',
    bg: '#f7fee7',
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'terracotta',
    label: 'Terracota',
    theme: 'Terracotta mediterráneo',
    dot: '#7c2d12',
    corner: '#c2410c',
    cornerDot: '#ca8a04',
    bg: '#fff7ed',
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'azul-maya',
    label: 'Azul maya',
    theme: 'Azul maya & oro artesanal',
    dot: '#0c4a6e',
    corner: '#0369a1',
    cornerDot: '#ca8a04',
    bg: '#fffbeb',
    dotStyle: 'classy-rounded',
  }),
  qrPreset({
    id: 'sakura',
    label: 'Sakura',
    theme: 'Sakura primavera japonesa',
    dot: '#9f1239',
    corner: '#e11d48',
    cornerDot: '#171717',
    bg: '#fff1f2',
    dotStyle: 'extra-rounded',
  }),

  // —— Transparentes ——
  qrPreset({
    id: 'transparent',
    label: 'Transparente',
    theme: 'Oscuro sobre cualquier fondo claro',
    dot: '#0f172a',
    bg: '#ffffff',
    transparent: true,
  }),
  qrPreset({
    id: 'transparent-light',
    label: 'Transp. oscuro',
    theme: 'QR oscuro para fondos claros',
    dot: '#020617',
    corner: '#1e293b',
    cornerDot: '#334155',
    bg: '#ffffff',
    transparent: true,
  }),
  qrPreset({
    id: 'transparent-wine',
    label: 'Transp. vino',
    theme: 'Borgoña para vitrinas claras',
    dot: '#581c87',
    corner: '#6b21a8',
    cornerDot: '#7e22ce',
    bg: '#ffffff',
    transparent: true,
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'transparent-neon',
    label: 'Transp. neón',
    theme: 'Oscuro neón para stickers',
    dot: '#0f172a',
    corner: '#be123c',
    cornerDot: '#0f172a',
    bg: '#ffffff',
    transparent: true,
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'transparent-gold',
    label: 'Transp. oro',
    theme: 'Oro premium vitrinas',
    dot: '#78350f',
    corner: '#92400e',
    cornerDot: '#ca8a04',
    bg: '#ffffff',
    transparent: true,
    dotStyle: 'classy',
  }),
  qrPreset({
    id: 'transparent-mint',
    label: 'Transp. menta',
    theme: 'Verde wellness stickers',
    dot: '#14532d',
    corner: '#166534',
    cornerDot: '#15803d',
    bg: '#ffffff',
    transparent: true,
    dotStyle: 'dots',
  }),
  qrPreset({
    id: 'transparent-coral',
    label: 'Transp. coral',
    theme: 'Coral vibrante menú',
    dot: '#9f1239',
    corner: '#be123c',
    cornerDot: '#e11d48',
    bg: '#ffffff',
    transparent: true,
    dotStyle: 'extra-rounded',
  }),
  qrPreset({
    id: 'transparent-light-dots',
    label: 'Transp. claro',
    theme: 'QR claro para fondos oscuros',
    dot: '#f8fafc',
    corner: '#e2e8f0',
    cornerDot: '#cbd5e1',
    bg: '#0f172a',
    transparent: true,
    dotStyle: 'rounded',
  }),
];
