"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-06-13 03:32:47.077451
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0001_baseline'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('actor', sa.String(length=255), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('target_table', sa.String(length=63), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_index('ix_audit_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_occurred', 'audit_logs', ['occurred_at'], unique=False)
    op.create_table('idempotency_keys',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('response_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_idempotency_keys'))
    )
    op.create_index('ix_idempotency_expires', 'idempotency_keys', ['expires_at'], unique=False)
    op.create_table('restaurants',
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('place_id', sa.Text(), nullable=True),
    sa.Column('logo_path', sa.Text(), nullable=True),
    sa.Column('subdomain', sa.String(length=63), nullable=False),
    sa.Column('color_palette', sa.String(length=50), nullable=True),
    sa.Column('original_language', sa.String(length=10), server_default='es', nullable=False),
    sa.Column('status', sa.String(), server_default='draft', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('draft','published','suspended')", name=op.f('ck_restaurants_status_allowed')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurants')),
    sa.UniqueConstraint('subdomain', name='uq_restaurants_subdomain')
    )
    op.create_table('ai_artifacts',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('optimized_value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), server_default='applied', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("entity_type IN ('product','category','restaurant')", name=op.f('ck_ai_artifacts_ai_entity_type_allowed')),
    sa.CheckConstraint("status IN ('applied','reverted')", name=op.f('ck_ai_artifacts_ai_artifact_status_allowed')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_ai_artifacts_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_artifacts'))
    )
    op.create_index('ix_ai_artifacts_entity', 'ai_artifacts', ['restaurant_id', 'entity_type', 'entity_id'], unique=False)
    op.create_table('categories',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('sort_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_categories_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories'))
    )
    op.create_index('ix_categories_listing', 'categories', ['restaurant_id', 'is_active', 'sort_index'], unique=False)
    op.create_table('menu_translations',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('locale', sa.String(length=10), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('translated_text', sa.Text(), nullable=False),
    sa.Column('source_hash', sa.String(length=64), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_menu_translations_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_menu_translations')),
    sa.UniqueConstraint('restaurant_id', 'locale', 'entity_type', 'entity_id', 'field', name='uq_menu_translation_unique')
    )
    op.create_index('ix_menu_translations_lookup', 'menu_translations', ['restaurant_id', 'locale', 'entity_type', 'entity_id'], unique=False)
    op.create_table('orders',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('customer_name', sa.Text(), nullable=False),
    sa.Column('customer_phone', sa.Text(), nullable=False),
    sa.Column('delivery_address', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=False),
    sa.Column('subtotal_cents', sa.Integer(), nullable=False),
    sa.Column('total_cents', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), server_default='pending', nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("payment_method IN ('cash','transfer','card_terminal')", name=op.f('ck_orders_order_payment_method_allowed')),
    sa.CheckConstraint("status IN ('pending','confirmed','preparing','ready','delivered','cancelled')", name=op.f('ck_orders_order_status_allowed')),
    sa.CheckConstraint("type IN ('takeout','delivery')", name=op.f('ck_orders_order_type_allowed')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_orders_restaurant_id_restaurants'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_index('ix_orders_listing', 'orders', ['restaurant_id', 'status', 'created_at'], unique=False)
    op.create_table('products',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price_cents', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), server_default='USD', nullable=False),
    sa.Column('image_path', sa.Text(), nullable=True),
    sa.Column('approval_status', sa.String(), server_default='draft', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("approval_status IN ('draft','pending_review','approved','rejected')", name=op.f('ck_products_approval_status_allowed')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_products_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_index('ix_products_publish', 'products', ['restaurant_id', 'is_active', 'is_published'], unique=False)
    op.create_index('ix_products_review', 'products', ['restaurant_id', 'approval_status'], unique=False)
    op.create_table('promotions',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('percent', sa.Integer(), nullable=True),
    sa.Column('amount_cents', sa.Integer(), nullable=True),
    sa.Column('scope', sa.String(), nullable=False),
    sa.Column('min_order_cents', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("scope IN ('product','category','order')", name=op.f('ck_promotions_promotion_scope_allowed')),
    sa.CheckConstraint("type IN ('percent','amount','combo','two_for_one')", name=op.f('ck_promotions_promotion_type_allowed')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_promotions_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_promotions'))
    )
    op.create_index('ix_promotions_active', 'promotions', ['restaurant_id', 'is_active'], unique=False)
    op.create_table('restaurant_payment_methods',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("method IN ('cash','transfer','card_terminal')", name=op.f('ck_restaurant_payment_methods_method_allowed')),
    sa.CheckConstraint("service_type IN ('takeout','delivery')", name=op.f('ck_restaurant_payment_methods_pm_service_type_allowed')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_restaurant_payment_methods_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurant_payment_methods')),
    sa.UniqueConstraint('restaurant_id', 'method', 'service_type', name='uq_payment_method_service')
    )
    op.create_table('restaurant_schedules',
    sa.Column('restaurant_id', sa.UUID(), nullable=False),
    sa.Column('service_type', sa.String(), nullable=False),
    sa.Column('day_of_week', sa.SmallInteger(), nullable=False),
    sa.Column('opens_at', sa.Time(), nullable=False),
    sa.Column('closes_at', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("service_type IN ('takeout','delivery')", name=op.f('ck_restaurant_schedules_service_type_allowed')),
    sa.CheckConstraint('day_of_week BETWEEN 0 AND 6', name=op.f('ck_restaurant_schedules_day_of_week_range')),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], name=op.f('fk_restaurant_schedules_restaurant_id_restaurants'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_restaurant_schedules'))
    )
    op.create_index('ix_schedules_lookup', 'restaurant_schedules', ['restaurant_id', 'service_type', 'day_of_week'], unique=False)
    op.create_table('option_groups',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('required', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('selection', sa.String(), nullable=False),
    sa.Column('min_selections', sa.Integer(), server_default='0', nullable=False),
    sa.Column('max_selections', sa.Integer(), nullable=True),
    sa.Column('sort_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("selection IN ('single','multi')", name=op.f('ck_option_groups_selection_allowed')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_option_groups_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_option_groups'))
    )
    op.create_index('ix_option_groups_product', 'option_groups', ['product_id'], unique=False)
    op.create_table('order_items',
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=True),
    sa.Column('product_name', sa.Text(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('unit_price_cents', sa.Integer(), nullable=False),
    sa.Column('selected_options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('line_total_cents', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_order_items_product_id_products'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_index('ix_order_items_order', 'order_items', ['order_id'], unique=False)
    op.create_table('product_categories',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_product_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_categories_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'category_id', name=op.f('pk_product_categories'))
    )
    op.create_table('promotion_categories',
    sa.Column('promotion_id', sa.UUID(), nullable=False),
    sa.Column('category_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_promotion_categories_category_id_categories'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], name=op.f('fk_promotion_categories_promotion_id_promotions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('promotion_id', 'category_id', name=op.f('pk_promotion_categories'))
    )
    op.create_table('promotion_products',
    sa.Column('promotion_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_promotion_products_product_id_products'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['promotion_id'], ['promotions.id'], name=op.f('fk_promotion_products_promotion_id_promotions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('promotion_id', 'product_id', name=op.f('pk_promotion_products'))
    )
    op.create_table('option_items',
    sa.Column('option_group_id', sa.UUID(), nullable=False),
    sa.Column('label', sa.Text(), nullable=False),
    sa.Column('price_delta_cents', sa.Integer(), server_default='0', nullable=False),
    sa.Column('sort_index', sa.Integer(), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['option_group_id'], ['option_groups.id'], name=op.f('fk_option_items_option_group_id_option_groups'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_option_items'))
    )
    op.create_index('ix_option_items_group', 'option_items', ['option_group_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_option_items_group', table_name='option_items')
    op.drop_table('option_items')
    op.drop_table('promotion_products')
    op.drop_table('promotion_categories')
    op.drop_table('product_categories')
    op.drop_index('ix_order_items_order', table_name='order_items')
    op.drop_table('order_items')
    op.drop_index('ix_option_groups_product', table_name='option_groups')
    op.drop_table('option_groups')
    op.drop_index('ix_schedules_lookup', table_name='restaurant_schedules')
    op.drop_table('restaurant_schedules')
    op.drop_table('restaurant_payment_methods')
    op.drop_index('ix_promotions_active', table_name='promotions')
    op.drop_table('promotions')
    op.drop_index('ix_products_review', table_name='products')
    op.drop_index('ix_products_publish', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_orders_listing', table_name='orders')
    op.drop_table('orders')
    op.drop_index('ix_menu_translations_lookup', table_name='menu_translations')
    op.drop_table('menu_translations')
    op.drop_index('ix_categories_listing', table_name='categories')
    op.drop_table('categories')
    op.drop_index('ix_ai_artifacts_entity', table_name='ai_artifacts')
    op.drop_table('ai_artifacts')
    op.drop_table('restaurants')
    op.drop_index('ix_idempotency_expires', table_name='idempotency_keys')
    op.drop_table('idempotency_keys')
    op.drop_index('ix_audit_occurred', table_name='audit_logs')
    op.drop_index('ix_audit_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
