import type { DigitalMenuTheme, DigitalMenuThemeColors } from './types';

function c(
  colors: Omit<
    DigitalMenuThemeColors,
    'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
  > &
    Partial<
      Pick<
        DigitalMenuThemeColors,
        'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
      >
    >,
): DigitalMenuThemeColors {
  return {
    ...colors,
    priceOriginal: colors.priceOriginal ?? colors.textSecondary,
    priceSale: colors.priceSale ?? colors.primary,
    discountBadgeBg: colors.discountBadgeBg ?? colors.background,
    discountBadgeText: colors.discountBadgeText ?? colors.primary,
  };
}

/** Themes 14–23 — generated via ui-ux-pro-max (--design-system + domain color/typography/style). */
export const EXTENDED_DIGITAL_MENU_THEMES: DigitalMenuTheme[] = [
  {
    id: 'korean-bbq',
    name: 'Korean BBQ',
    label: 'K-BBQ',
    description: 'Rojo intenso y negro carbón con tipografía coreana limpia. Ideal para parrilla coreana.',
    bestFor: ['Korean BBQ', 'Parrilla asiática', 'Hot pot'],
    designSystemQuery: 'korean bbq restaurant menu',
    typography: {
      headingFont: '"Noto Sans KR", system-ui, sans-serif',
      bodyFont: '"Noto Sans KR", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@300;400;500;700&display=swap',
      mood: 'korean, modern, clean, bold',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['bold', 'block layout', 'high contrast', 'energetic'],
      borderRadius: 'sharp',
      cardRadiusPx: 10,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#CD2E3A',
      secondary: '#1F2937',
      accent: '#0047A0',
      background: '#FFF8F6',
      surface: '#FFFFFF',
      text: '#1F2937',
      textMuted: '#4B5563',
      textSecondary: '#6B7280',
      border: '#FECACA',
      categoryActive: '#FFFFFF',
      categoryIndicator: '#CD2E3A',
      price: '#1F2937',
      coverPlaceholderFrom: '#F87171',
      coverPlaceholderTo: '#CD2E3A',
      coverScrim: 'linear-gradient(to top, rgba(31, 41, 55, 0.4), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#1F2937',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FEE2E2',
      productThumbBg: '#F3F4F6',
    }),
  },
  {
    id: 'curry-india',
    name: 'Curry India',
    label: 'Curry',
    description: 'Azafrán, naranja especiado y dorado cálido con serif editorial.',
    bestFor: ['Comida india', 'Curry house', 'Tandoori'],
    designSystemQuery: 'indian restaurant warm spices',
    typography: {
      headingFont: '"Playfair Display SC", Georgia, serif',
      bodyFont: 'Karla, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Karla:wght@300;400;500;600;700&family=Playfair+Display+SC:wght@400;700&display=swap',
      mood: 'restaurant, culinary, warm, hospitality',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['warm', 'spices', 'bold', 'inviting'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#EA580C',
      secondary: '#D97706',
      accent: '#CA8A04',
      background: '#FFFBEB',
      surface: '#FFFFFF',
      text: '#7C2D0E',
      textMuted: '#9A3412',
      textSecondary: '#C2410C',
      border: '#FED7AA',
      categoryActive: '#7C2D0E',
      categoryIndicator: '#EA580C',
      price: '#7C2D0E',
      coverPlaceholderFrom: '#FDBA74',
      coverPlaceholderTo: '#EA580C',
      coverScrim: 'linear-gradient(to top, rgba(124, 45, 14, 0.35), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.93)',
      floatButtonText: '#7C2D0E',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FFEDD5',
      productThumbBg: '#FFEDD5',
    }),
  },
  {
    id: 'bistro-frances',
    name: 'Bistro Francés',
    label: 'Bistro',
    description: 'Marino elegante y acentos dorados — estilo hotel/bistro parisino.',
    bestFor: ['Bistro francés', 'Brasserie', 'Crepes y vinos'],
    designSystemQuery: 'french bistro navy gold',
    typography: {
      headingFont: 'Cormorant, Georgia, serif',
      bodyFont: 'Montserrat, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Cormorant:wght@400;500;600;700&family=Montserrat:wght@300;400;500;600;700&display=swap',
      mood: 'luxury, elegant, refined, premium',
    },
    style: {
      name: 'Liquid Glass',
      keywords: ['luxury', 'refined', 'editorial', 'hospitality'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#1E3A8A',
      secondary: '#3B82F6',
      accent: '#CA8A04',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      text: '#1E40AF',
      textMuted: '#334155',
      textSecondary: '#64748B',
      border: '#DBEAFE',
      categoryActive: '#1E3A8A',
      categoryIndicator: '#CA8A04',
      price: '#1E3A8A',
      coverPlaceholderFrom: '#93C5FD',
      coverPlaceholderTo: '#1E3A8A',
      coverScrim: 'linear-gradient(to top, rgba(30, 58, 138, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#1E3A8A',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#EFF6FF',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'bbq-humo',
    name: 'BBQ Humo',
    label: 'BBQ',
    description: 'Marrón ahumado y ámbar rústico con tipografía craft handmade.',
    bestFor: ['Smokehouse', 'Parrilla BBQ', 'Costillas y brisket'],
    designSystemQuery: 'bbq smokehouse restaurant rustic',
    typography: {
      headingFont: '"Amatic SC", cursive',
      bodyFont: 'Cabin, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&family=Cabin:wght@400;500;600;700&display=swap',
      mood: 'indie, craft, artisan, rustic',
    },
    style: {
      name: 'Organic Biophilic',
      keywords: ['rustic', 'smoke', 'earthy', 'artisan'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#78350F',
      secondary: '#92400E',
      accent: '#F59E0B',
      background: '#FEF3C7',
      surface: '#FFFBEB',
      text: '#451A03',
      textMuted: '#78350F',
      textSecondary: '#92400E',
      border: '#FDE68A',
      categoryActive: '#FFFBEB',
      categoryIndicator: '#78350F',
      price: '#451A03',
      coverPlaceholderFrom: '#D97706',
      coverPlaceholderTo: '#451A03',
      coverScrim: 'linear-gradient(to top, rgba(69, 26, 3, 0.45), transparent)',
      floatButtonBg: 'rgba(255, 251, 235, 0.92)',
      floatButtonText: '#451A03',
      logoBorder: '#FFFBEB',
      logoPlaceholderBg: '#FEF3C7',
      productThumbBg: '#FEF3C7',
    }),
  },
  {
    id: 'vegan-verde',
    name: 'Vegan Verde',
    label: 'Vegan',
    description: 'Verde tierra y dorado cosecha — estilo agricultura/plant-based.',
    bestFor: ['Vegan', 'Plant-based', 'Orgánico'],
    designSystemQuery: 'vegan green earth',
    typography: {
      headingFont: 'Fraunces, Georgia, serif',
      bodyFont: '"DM Sans", system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Fraunces:wght@500;600;700&display=swap',
      mood: 'natural, organic, calm, sustainable',
    },
    style: {
      name: 'Organic Biophilic',
      keywords: ['nature', 'green', 'sustainable', 'wellness'],
      borderRadius: 'pill',
      cardRadiusPx: 18,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#15803D',
      secondary: '#22C55E',
      accent: '#CA8A04',
      background: '#F0FDF4',
      surface: '#FFFFFF',
      text: '#14532D',
      textMuted: '#166534',
      textSecondary: '#15803D',
      border: '#BBF7D0',
      categoryActive: '#14532D',
      categoryIndicator: '#15803D',
      price: '#14532D',
      coverPlaceholderFrom: '#86EFAC',
      coverPlaceholderTo: '#15803D',
      coverScrim: 'linear-gradient(to top, rgba(20, 83, 45, 0.3), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#14532D',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#DCFCE7',
      productThumbBg: '#DCFCE7',
    }),
  },
  {
    id: 'cava-vino',
    name: 'Cava y Vino',
    label: 'Vino',
    description: 'Borgoña profundo y oro craft — bodega y wine bar.',
    bestFor: ['Wine bar', 'Bodega', 'Tapas y quesos'],
    designSystemQuery: 'wine bar brewery restaurant',
    typography: {
      headingFont: 'Cormorant, Georgia, serif',
      bodyFont: 'Montserrat, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Cormorant:wght@400;500;600;700&family=Montserrat:wght@300;400;500;600;700&display=swap',
      mood: 'luxury, cellar, refined, premium',
    },
    style: {
      name: 'Motion-Driven',
      keywords: ['premium', 'craft', 'elegant', 'hospitality'],
      borderRadius: 'rounded',
      cardRadiusPx: 10,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#7C2D12',
      secondary: '#B91C1C',
      accent: '#CA8A04',
      background: '#FEF2F2',
      surface: '#FFFFFF',
      text: '#450A0A',
      textMuted: '#7F1D1D',
      textSecondary: '#991B1B',
      border: '#FECACA',
      categoryActive: '#450A0A',
      categoryIndicator: '#7C2D12',
      price: '#450A0A',
      coverPlaceholderFrom: '#B91C1C',
      coverPlaceholderTo: '#7C2D12',
      coverScrim: 'linear-gradient(to top, rgba(69, 10, 10, 0.38), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#450A0A',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FEE2E2',
      productThumbBg: '#FEE2E2',
    }),
  },
  {
    id: 'diner-retro',
    name: 'Diner Retro',
    label: 'Diner Retro',
    description: 'Estilo retro americano con tipografía pixel y acentos naranja.',
    bestFor: ['Diner', 'Desayunos', 'Comida americana clásica'],
    designSystemQuery: 'breakfast diner retro american',
    typography: {
      headingFont: '"Press Start 2P", monospace',
      bodyFont: 'VT323, monospace',
      headingWeight: 400,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Press+Start+2P&family=VT323&display=swap',
      mood: 'pixel, retro, nostalgic, arcade',
    },
    style: {
      name: 'Retro-Futurism',
      keywords: ['retro', 'neon', 'vintage', 'playful'],
      borderRadius: 'sharp',
      cardRadiusPx: 8,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#2563EB',
      secondary: '#3B82F6',
      accent: '#F97316',
      background: '#F8FAFC',
      surface: '#FFFFFF',
      text: '#1E293B',
      textMuted: '#475569',
      textSecondary: '#64748B',
      border: '#E2E8F0',
      categoryActive: '#FFFFFF',
      categoryIndicator: '#2563EB',
      price: '#1E293B',
      coverPlaceholderFrom: '#93C5FD',
      coverPlaceholderTo: '#2563EB',
      coverScrim: 'linear-gradient(to top, rgba(30, 41, 59, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#1E293B',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#EFF6FF',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'mediterraneo',
    name: 'Mediterráneo',
    label: 'Mediterráneo',
    description: 'Terracota, oliva y crema — estética nature distilled artesanal.',
    bestFor: ['Griego', 'Turco', 'Falafel', 'Hummus bar'],
    designSystemQuery: 'middle eastern terracotta gold',
    typography: {
      headingFont: '"Cormorant Garamond", Georgia, serif',
      bodyFont: '"Source Sans 3", system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=Source+Sans+3:wght@300;400;500;600;700&display=swap',
      mood: 'artisan, warm, mediterranean, natural',
    },
    style: {
      name: 'Organic Biophilic',
      keywords: ['terracotta', 'earth', 'handmade', 'warm'],
      borderRadius: 'soft',
      cardRadiusPx: 16,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#C67B5C',
      secondary: '#6B7B3C',
      accent: '#CA8A04',
      background: '#F5F0E1',
      surface: '#FFFBF5',
      text: '#5C4033',
      textMuted: '#78716C',
      textSecondary: '#92400E',
      border: '#E7D5C4',
      categoryActive: '#5C4033',
      categoryIndicator: '#C67B5C',
      price: '#5C4033',
      coverPlaceholderFrom: '#D4C4A8',
      coverPlaceholderTo: '#C67B5C',
      coverScrim: 'linear-gradient(to top, rgba(92, 64, 51, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 251, 245, 0.94)',
      floatButtonText: '#5C4033',
      logoBorder: '#FFFBF5',
      logoPlaceholderBg: '#EDE4D4',
      productThumbBg: '#EDE4D4',
    }),
  },
  {
    id: 'thai-vibrante',
    name: 'Thai Vibrante',
    label: 'Thai',
    description: 'Verde albahaca y naranja tailandés con Noto Sans Thai.',
    bestFor: ['Comida tailandesa', 'Pad thai', 'Street food asiático'],
    designSystemQuery: 'thai orange basil green',
    typography: {
      headingFont: '"Noto Sans Thai", system-ui, sans-serif',
      bodyFont: '"Noto Sans Thai", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Noto+Sans+Thai:wght@300;400;500;700&display=swap',
      mood: 'thai, modern, clean, vibrant',
    },
    style: {
      name: 'Aurora Gradient',
      keywords: ['vibrant', 'fresh', 'colorful', 'flowing'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#059669',
      secondary: '#10B981',
      accent: '#F97316',
      background: '#ECFDF5',
      surface: '#FFFFFF',
      text: '#064E3B',
      textMuted: '#047857',
      textSecondary: '#059669',
      border: '#A7F3D0',
      categoryActive: '#064E3B',
      categoryIndicator: '#F97316',
      price: '#064E3B',
      coverPlaceholderFrom: '#6EE7B7',
      coverPlaceholderTo: '#059669',
      coverScrim: 'linear-gradient(to top, rgba(6, 78, 59, 0.34), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.93)',
      floatButtonText: '#064E3B',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#D1FAE5',
      productThumbBg: '#D1FAE5',
    }),
  },
  {
    id: 'ramen-miso',
    name: 'Ramen Miso',
    label: 'Ramen',
    description: 'Tonos miso cálidos y tipografía japonesa serif + sans.',
    bestFor: ['Ramen', 'Udon', 'Cocina japonesa casual'],
    designSystemQuery: 'ramen miso warm brown',
    typography: {
      headingFont: '"Noto Serif JP", Georgia, serif',
      bodyFont: '"Noto Sans JP", system-ui, sans-serif',
      headingWeight: 500,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500;700&family=Noto+Serif+JP:wght@400;500;600;700&display=swap',
      mood: 'japanese, warm, steam, comfort',
    },
    style: {
      name: 'Organic Biophilic',
      keywords: ['warm', 'comfort', 'earthy', 'steam'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#92400E',
      secondary: '#B45309',
      accent: '#CA8A04',
      background: '#FEF3C7',
      surface: '#FFFBEB',
      text: '#78350F',
      textMuted: '#92400E',
      textSecondary: '#B45309',
      border: '#FDE68A',
      categoryActive: '#78350F',
      categoryIndicator: '#92400E',
      price: '#78350F',
      coverPlaceholderFrom: '#FCD34D',
      coverPlaceholderTo: '#92400E',
      coverScrim: 'linear-gradient(to top, rgba(120, 53, 15, 0.36), transparent)',
      floatButtonBg: 'rgba(255, 251, 235, 0.93)',
      floatButtonText: '#78350F',
      logoBorder: '#FFFBEB',
      logoPlaceholderBg: '#FEF3C7',
      productThumbBg: '#FEF3C7',
    }),
  },
  {
    id: 'poke-hawaiian',
    name: 'Poke Hawaiian',
    label: 'Poke',
    description: 'Cian tropical y verde fresco — glassmorphism hawaiano.',
    bestFor: ['Poke bowl', 'Hawaiian', 'Comida fresca de playa'],
    designSystemQuery: 'hawaiian poke tropical fresh',
    typography: {
      headingFont: 'Fredoka, system-ui, sans-serif',
      bodyFont: 'Nunito, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Nunito:wght@300;400;500;600;700&display=swap',
      mood: 'playful, friendly, tropical, fresh',
    },
    style: {
      name: 'Glassmorphism',
      keywords: ['frosted', 'fresh', 'layered', 'tropical'],
      borderRadius: 'soft',
      cardRadiusPx: 16,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#0891B2',
      secondary: '#22D3EE',
      accent: '#22C55E',
      background: '#ECFEFF',
      surface: '#FFFFFF',
      text: '#164E63',
      textMuted: '#155E75',
      textSecondary: '#0E7490',
      border: '#A5F3FC',
      categoryActive: '#164E63',
      categoryIndicator: '#0891B2',
      price: '#164E63',
      coverPlaceholderFrom: '#67E8F9',
      coverPlaceholderTo: '#0891B2',
      coverScrim: 'linear-gradient(to top, rgba(22, 78, 99, 0.3), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#164E63',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#CFFAFE',
      productThumbBg: '#CFFAFE',
    }),
  },
  {
    id: 'steak-carbon',
    name: 'Steak Carbon',
    label: 'Steak',
    description: 'Carbón oscuro, rojo carne y oro — steakhouse premium.',
    bestFor: ['Steakhouse', 'Carnes', 'Asador premium'],
    designSystemQuery: 'steakhouse restaurant premium dark',
    typography: {
      headingFont: '"Libre Baskerville", Georgia, serif',
      bodyFont: '"DM Sans", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;500;700&family=Libre+Baskerville:wght@400;700&display=swap',
      mood: 'premium, sophisticated, bold, classic',
    },
    style: {
      name: 'Liquid Glass',
      keywords: ['premium', 'dark', 'luxury', 'refined'],
      borderRadius: 'sharp',
      cardRadiusPx: 10,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#991B1B',
      secondary: '#44403C',
      accent: '#CA8A04',
      background: '#171717',
      surface: '#262626',
      text: '#F5F5F5',
      textMuted: '#D4D4D4',
      textSecondary: '#A3A3A3',
      border: '#404040',
      categoryActive: '#FAFAFA',
      categoryIndicator: '#CA8A04',
      price: '#F5F5F5',
      coverPlaceholderFrom: '#525252',
      coverPlaceholderTo: '#171717',
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.55), transparent)',
      floatButtonBg: 'rgba(38, 38, 38, 0.92)',
      floatButtonText: '#F5F5F5',
      logoBorder: '#262626',
      logoPlaceholderBg: '#404040',
      productThumbBg: '#404040',
    }),
  },
];
