import type { DigitalMenuTheme, DigitalMenuThemeColors } from './types';

function c(
  colors: Omit<
    DigitalMenuThemeColors,
    'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
  > &
    Partial<
      Pick<
        DigitalMenuThemeColors,
        'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
      >
    >,
): DigitalMenuThemeColors {
  return {
    ...colors,
    priceOriginal: colors.priceOriginal ?? colors.textSecondary,
    priceSale: colors.priceSale ?? colors.primary,
    discountBadgeBg: colors.discountBadgeBg ?? colors.background,
    discountBadgeText: colors.discountBadgeText ?? colors.primary,
  };
}

/**
 * Soft & color — white page background with tinted surfaces, vivid accents,
 * and expressive typography (first essentials expansion, original look restored).
 */
export const SOFT_COLOR_DIGITAL_MENU_THEMES: DigitalMenuTheme[] = [

  // ── Soft / rounded bold ──────────────────────────────────────────────
  {
    id: 'soft-order',
    name: 'Soft Order',
    label: 'Soft Order',
    description:
      'Fondo blanco con coral cálido y tipografía Nunito Black redondeada. Sensación friendly tipo “Start an Order”.',
    bestFor: ['Cualquier restaurante', 'Delivery app', 'Marcas amigables'],
    context:
      'Blanco puro, coral #F97316 y charcoal suave con Nunito Black (terminals redondeados). Premium-casual, legible y cercano — como un CTA de pedido moderno.',
    recommendation:
      'Restaurantes generales, dark kitchens y marcas que quieren verse modernas y accesibles sin atarse a una cocina específica.',
    designSystemQuery: 'soft rounded bold friendly food ordering white background coral',
    typography: {
      headingFont: 'Nunito, system-ui, sans-serif',
      bodyFont: '"DM Sans", system-ui, sans-serif',
      headingWeight: 900,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400&family=Nunito:ital,wght@0,700;0,800;0,900;1,700&display=swap',
      mood: 'soft, rounded, bold, friendly, approachable',
    },
    style: {
      name: 'Exaggerated Minimalism',
      keywords: ['soft', 'rounded', 'coral', 'white', 'bold type'],
      borderRadius: 'soft',
      cardRadiusPx: 16,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#EA580C',
      secondary: '#FB923C',
      accent: '#F97316',
      background: '#FFFFFF',
      surface: '#FFF7ED',
      text: '#1C1917',
      textMuted: '#78716C',
      textSecondary: '#A8A29E',
      border: '#FFEDD5',
      categoryActive: '#9A3412',
      categoryIndicator: '#F97316',
      price: '#1C1917',
      priceOriginal: '#A8A29E',
      priceSale: '#EA580C',
      discountBadgeBg: '#FFF7ED',
      discountBadgeText: '#C2410C',
      coverPlaceholderFrom: '#FDBA74',
      coverPlaceholderTo: '#EA580C',
      coverScrim: 'linear-gradient(to top, rgba(28, 25, 23, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#1C1917',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FFEDD5',
      productThumbBg: '#FFF7ED',
    }),
  },
  {
    id: 'bubble-mint',
    name: 'Bubble Mint',
    label: 'Bubble Mint',
    description: 'Blanco + menta fresca con Fredoka redondeada. Limpio, juguetón y versátil.',
    bestFor: ['Cualquier restaurante', 'Healthy casual', 'Pedidos rápidos'],
    context:
      'Fondo blanco, menta #10B981 y superficies mint muy suaves con Fredoka/Nunito. Fresco y bubble-like sin perder profesionalismo.',
    recommendation:
      'Menús generales, bowls, cafés ligeros o cualquier marca que quiera transmitir frescura y facilidad de pedido.',
    designSystemQuery: 'mint green soft rounded fredoka white menu',
    typography: {
      headingFont: 'Fredoka, system-ui, sans-serif',
      bodyFont: 'Nunito, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Nunito:wght@300;400;500;600;700&display=swap',
      mood: 'playful, soft, mint, friendly',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['mint', 'soft', 'rounded', 'fresh', 'white'],
      borderRadius: 'soft',
      cardRadiusPx: 16,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#059669',
      secondary: '#34D399',
      accent: '#10B981',
      background: '#FFFFFF',
      surface: '#ECFDF5',
      text: '#064E3B',
      textMuted: '#047857',
      textSecondary: '#6B7280',
      border: '#D1FAE5',
      categoryActive: '#064E3B',
      categoryIndicator: '#10B981',
      price: '#064E3B',
      priceOriginal: '#6B7280',
      priceSale: '#059669',
      discountBadgeBg: '#ECFDF5',
      discountBadgeText: '#047857',
      coverPlaceholderFrom: '#6EE7B7',
      coverPlaceholderTo: '#059669',
      coverScrim: 'linear-gradient(to top, rgba(6, 78, 59, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#064E3B',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#D1FAE5',
      productThumbBg: '#ECFDF5',
    }),
  },
  {
    id: 'peach-soft',
    name: 'Peach Soft',
    label: 'Peach Soft',
    description: 'Durazno rosado sobre blanco con Varela Round. Cálido, suave y acogedor.',
    bestFor: ['Cualquier restaurante', 'Brunch casual', 'Marcas soft'],
    context:
      'Blanco, peach-rose #FB7185 y tipografía Varela Round + Nunito Sans. Soft UI amable, sin ser infantil.',
    recommendation:
      'Restaurantes familiares, brunch, panaderías ligeras o marcas con tono cálido y cercano.',
    designSystemQuery: 'peach rose soft rounded varela white background',
    typography: {
      headingFont: '"Varela Round", system-ui, sans-serif',
      bodyFont: '"Nunito Sans", system-ui, sans-serif',
      headingWeight: 400,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;500;600;700&family=Varela+Round&display=swap',
      mood: 'soft, rounded, warm, gentle',
    },
    style: {
      name: 'Organic Biophilic',
      keywords: ['peach', 'soft', 'warm', 'rounded', 'white'],
      borderRadius: 'pill',
      cardRadiusPx: 18,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#E11D48',
      secondary: '#FB7185',
      accent: '#F43F5E',
      background: '#FFFFFF',
      surface: '#FFF1F2',
      text: '#4C0519',
      textMuted: '#9F1239',
      textSecondary: '#9F1239',
      border: '#FFE4E6',
      categoryActive: '#4C0519',
      categoryIndicator: '#F43F5E',
      price: '#4C0519',
      priceOriginal: '#A8A29E',
      priceSale: '#E11D48',
      discountBadgeBg: '#FFF1F2',
      discountBadgeText: '#BE123C',
      coverPlaceholderFrom: '#FDA4AF',
      coverPlaceholderTo: '#E11D48',
      coverScrim: 'linear-gradient(to top, rgba(76, 5, 25, 0.3), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#4C0519',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FFE4E6',
      productThumbBg: '#FFF1F2',
    }),
  },
  {
    id: 'berry-soft',
    name: 'Berry Soft',
    label: 'Berry Soft',
    description: 'Mora/magenta sobre blanco con Nunito ExtraBold. Moderno y con carácter.',
    bestFor: ['Cualquier restaurante', 'Marcas young', 'Delivery'],
    context:
      'Blanco, berry #C026D3 y Nunito 800 + DM Sans. Soft-bold con acento frutal — distintivo pero usable para cualquier menú.',
    recommendation:
      'Marcas con personalidad joven, menús mixtos o quien quiera un acento memorable sin salir de Esenciales.',
    designSystemQuery: 'berry magenta soft bold nunito white menu',
    typography: {
      headingFont: 'Nunito, system-ui, sans-serif',
      bodyFont: '"DM Sans", system-ui, sans-serif',
      headingWeight: 800,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400&family=Nunito:ital,wght@0,700;0,800;0,900;1,700&display=swap',
      mood: 'bold, soft, berry, modern',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['berry', 'magenta', 'soft bold', 'white'],
      borderRadius: 'soft',
      cardRadiusPx: 16,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#A21CAF',
      secondary: '#E879F9',
      accent: '#C026D3',
      background: '#FFFFFF',
      surface: '#FDF4FF',
      text: '#4A044E',
      textMuted: '#86198F',
      textSecondary: '#A855F7',
      border: '#FAE8FF',
      categoryActive: '#4A044E',
      categoryIndicator: '#C026D3',
      price: '#4A044E',
      priceOriginal: '#A8A29E',
      priceSale: '#A21CAF',
      discountBadgeBg: '#FDF4FF',
      discountBadgeText: '#A21CAF',
      coverPlaceholderFrom: '#E879F9',
      coverPlaceholderTo: '#A21CAF',
      coverScrim: 'linear-gradient(to top, rgba(74, 4, 78, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#4A044E',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FAE8FF',
      productThumbBg: '#FDF4FF',
    }),
  },
  {
    id: 'sky-soft',
    name: 'Sky Soft',
    label: 'Sky Soft',
    description: 'Azul cielo sobre blanco con Baloo 2. Alegre, claro y fácil de leer.',
    bestFor: ['Cualquier restaurante', 'Familiar', 'Pedidos móviles'],
    context:
      'Blanco, sky #0EA5E9 y Baloo 2 + Quicksand. Tipografía soft y redonda; paleta fresca tipo cielo despejado.',
    recommendation:
      'Restaurantes familiares, menús para todos o marcas que buscan claridad y un tono positivo.',
    designSystemQuery: 'sky blue soft baloo quicksand white digital menu',
    typography: {
      headingFont: '"Baloo 2", system-ui, sans-serif',
      bodyFont: 'Quicksand, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 500,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Baloo+2:wght@400;500;600;700&family=Quicksand:wght@400;500;600;700&display=swap',
      mood: 'playful, soft, sky, friendly',
    },
    style: {
      name: 'Exaggerated Minimalism',
      keywords: ['sky', 'soft', 'rounded', 'clear', 'white'],
      borderRadius: 'soft',
      cardRadiusPx: 16,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#0284C7',
      secondary: '#38BDF8',
      accent: '#0EA5E9',
      background: '#FFFFFF',
      surface: '#F0F9FF',
      text: '#0C4A6E',
      textMuted: '#0369A1',
      textSecondary: '#64748B',
      border: '#E0F2FE',
      categoryActive: '#0C4A6E',
      categoryIndicator: '#0EA5E9',
      price: '#0C4A6E',
      priceOriginal: '#94A3B8',
      priceSale: '#0284C7',
      discountBadgeBg: '#F0F9FF',
      discountBadgeText: '#0369A1',
      coverPlaceholderFrom: '#7DD3FC',
      coverPlaceholderTo: '#0284C7',
      coverScrim: 'linear-gradient(to top, rgba(12, 74, 110, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#0C4A6E',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#E0F2FE',
      productThumbBg: '#F0F9FF',
    }),
  },
  {
    id: 'citrus-soft',
    name: 'Citrus Soft',
    label: 'Citrus Soft',
    description: 'Lima cítrica sobre blanco con Fredoka. Energético, fresco y versátil.',
    bestFor: ['Cualquier restaurante', 'Casual', 'Promos'],
    context:
      'Blanco, citrus lime #84CC16 y Fredoka/Nunito. Energía ácida-fresca; tipografía soft-bold como la referencia de pedido.',
    recommendation:
      'Menús casuales, promos visibles y marcas que quieren un acento vivo sin oscurecer el fondo.',
    designSystemQuery: 'citrus lime soft fredoka white food menu',
    typography: {
      headingFont: 'Fredoka, system-ui, sans-serif',
      bodyFont: 'Nunito, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Nunito:wght@300;400;500;600;700&display=swap',
      mood: 'energetic, soft, citrus, playful',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['citrus', 'lime', 'soft', 'energetic', 'white'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#65A30D',
      secondary: '#A3E635',
      accent: '#84CC16',
      background: '#FFFFFF',
      surface: '#F7FEE7',
      text: '#1A2E05',
      textMuted: '#4D7C0F',
      textSecondary: '#64748B',
      border: '#ECFCCB',
      categoryActive: '#1A2E05',
      categoryIndicator: '#84CC16',
      price: '#1A2E05',
      priceOriginal: '#94A3B8',
      priceSale: '#65A30D',
      discountBadgeBg: '#F7FEE7',
      discountBadgeText: '#4D7C0F',
      coverPlaceholderFrom: '#A3E635',
      coverPlaceholderTo: '#65A30D',
      coverScrim: 'linear-gradient(to top, rgba(26, 46, 5, 0.3), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#1A2E05',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#ECFCCB',
      productThumbBg: '#F7FEE7',
    }),
  },

  // ── Clean / geometric ────────────────────────────────────────────────
  {
    id: 'ink-blue',
    name: 'Ink Blue',
    label: 'Ink Blue',
    description: 'Azul confianza sobre blanco con Outfit geométrico. Limpio y profesional.',
    bestFor: ['Cualquier restaurante', 'Delivery', 'Marca confiable'],
    context:
      'Blanco, azul #2563EB y Outfit/Work Sans. Sensación logística/delivery confiable sin salir del look esencial.',
    recommendation:
      'Restaurantes con fuerte canal delivery, cadenas o quien prioriza claridad y confianza.',
    designSystemQuery: 'trust blue geometric outfit white digital menu',
    typography: {
      headingFont: 'Outfit, system-ui, sans-serif',
      bodyFont: '"Work Sans", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=Work+Sans:wght@300;400;500;600;700&display=swap',
      mood: 'geometric, modern, clean, trust',
    },
    style: {
      name: 'Minimalism',
      keywords: ['blue', 'trust', 'geometric', 'clean', 'white'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#2563EB',
      secondary: '#60A5FA',
      accent: '#3B82F6',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      text: '#1E3A8A',
      textMuted: '#475569',
      textSecondary: '#94A3B8',
      border: '#DBEAFE',
      categoryActive: '#1E3A8A',
      categoryIndicator: '#2563EB',
      price: '#1E3A8A',
      priceOriginal: '#94A3B8',
      priceSale: '#2563EB',
      discountBadgeBg: '#EFF6FF',
      discountBadgeText: '#1D4ED8',
      coverPlaceholderFrom: '#93C5FD',
      coverPlaceholderTo: '#2563EB',
      coverScrim: 'linear-gradient(to top, rgba(30, 58, 138, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#1E3A8A',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#DBEAFE',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'forest-clean',
    name: 'Forest Clean',
    label: 'Forest',
    description: 'Verde bosque sobre blanco con Poppins. Natural, limpio y equilibrado.',
    bestFor: ['Cualquier restaurante', 'Fresh', 'Plant-forward casual'],
    context:
      'Blanco, forest #059669 y Poppins/Open Sans. Clean geometric con acento vegetal — versátil para casi cualquier menú.',
    recommendation:
      'Restaurantes que quieren un acento verde serio (no neón) y tipografía profesional amigable.',
    designSystemQuery: 'forest green poppins clean white restaurant menu',
    typography: {
      headingFont: 'Poppins, system-ui, sans-serif',
      bodyFont: '"Open Sans", system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&family=Poppins:wght@400;500;600;700&display=swap',
      mood: 'modern, professional, clean, natural',
    },
    style: {
      name: 'Minimalism',
      keywords: ['forest', 'green', 'clean', 'professional', 'white'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#047857',
      secondary: '#34D399',
      accent: '#059669',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      text: '#022C22',
      textMuted: '#475569',
      textSecondary: '#94A3B8',
      border: '#D1FAE5',
      categoryActive: '#022C22',
      categoryIndicator: '#059669',
      price: '#022C22',
      priceOriginal: '#94A3B8',
      priceSale: '#047857',
      discountBadgeBg: '#ECFDF5',
      discountBadgeText: '#047857',
      coverPlaceholderFrom: '#6EE7B7',
      coverPlaceholderTo: '#047857',
      coverScrim: 'linear-gradient(to top, rgba(2, 44, 34, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#022C22',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#D1FAE5',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'amber-pulse',
    name: 'Amber Pulse',
    label: 'Amber',
    description: 'Naranja delivery sobre blanco con Outfit. Apetitoso y listo para pedir.',
    bestFor: ['Cualquier restaurante', 'Delivery', 'Fast casual'],
    context:
      'Blanco, amber-orange #EA580C (paleta food delivery ui-ux-pro-max) y Outfit/Work Sans. Apetitoso, claro y conversivo.',
    recommendation:
      'Negocios con foco en pedidos online, combos y CTAs visibles sin fondo tintado.',
    designSystemQuery: 'food delivery appetizing orange white background outfit',
    typography: {
      headingFont: 'Outfit, system-ui, sans-serif',
      bodyFont: '"Work Sans", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=Work+Sans:wght@300;400;500;600;700&display=swap',
      mood: 'appetizing, modern, delivery, clean',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['amber', 'orange', 'delivery', 'appetite', 'white'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#EA580C',
      secondary: '#FB923C',
      accent: '#F97316',
      background: '#FFFFFF',
      surface: '#FFFBEB',
      text: '#0F172A',
      textMuted: '#57534E',
      textSecondary: '#A8A29E',
      border: '#FED7AA',
      categoryActive: '#FFFFFF',
      categoryIndicator: '#EA580C',
      price: '#0F172A',
      priceOriginal: '#A8A29E',
      priceSale: '#EA580C',
      discountBadgeBg: '#FFF7ED',
      discountBadgeText: '#C2410C',
      coverPlaceholderFrom: '#FDBA74',
      coverPlaceholderTo: '#EA580C',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.3), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#0F172A',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FFEDD5',
      productThumbBg: '#FFFBEB',
    }),
  },
  {
    id: 'slate-indigo',
    name: 'Slate Indigo',
    label: 'Indigo',
    description: 'Índigo contemporáneo sobre blanco con Poppins. Serio, moderno y neutro.',
    bestFor: ['Cualquier restaurante', 'Premium casual', 'Marca tech'],
    context:
      'Blanco, indigo #4F46E5 y Poppins/Open Sans. Esencial contemporáneo — menos “food color”, más marca moderna.',
    recommendation:
      'Restaurantes con identidad tech/moderna o menús que prefieren un acento frío elegante.',
    designSystemQuery: 'indigo slate poppins modern white menu',
    typography: {
      headingFont: 'Poppins, system-ui, sans-serif',
      bodyFont: '"Open Sans", system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&family=Poppins:wght@400;500;600;700&display=swap',
      mood: 'modern, professional, indigo, clean',
    },
    style: {
      name: 'Minimalism',
      keywords: ['indigo', 'slate', 'modern', 'clean', 'white'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#4F46E5',
      secondary: '#818CF8',
      accent: '#6366F1',
      background: '#FFFFFF',
      surface: '#F8FAFC',
      text: '#1E1B4B',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#E0E7FF',
      categoryActive: '#1E1B4B',
      categoryIndicator: '#4F46E5',
      price: '#1E1B4B',
      priceOriginal: '#94A3B8',
      priceSale: '#4F46E5',
      discountBadgeBg: '#EEF2FF',
      discountBadgeText: '#4338CA',
      coverPlaceholderFrom: '#A5B4FC',
      coverPlaceholderTo: '#4F46E5',
      coverScrim: 'linear-gradient(to top, rgba(30, 27, 75, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#1E1B4B',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#E0E7FF',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'teal-trust',
    name: 'Teal Trust',
    label: 'Teal',
    description: 'Teal equilibrado sobre blanco con Outfit. Fresco, confiable y limpio.',
    bestFor: ['Cualquier restaurante', 'Casual moderno', 'Delivery'],
    context:
      'Blanco, teal #0D9488 y Outfit/Work Sans. Entre azul y verde: fresco, estable y muy usable como esencial.',
    recommendation:
      'Menús generales que quieren un acento fresco distinto al verde delivery clásico.',
    designSystemQuery: 'teal trust outfit clean white restaurant',
    typography: {
      headingFont: 'Outfit, system-ui, sans-serif',
      bodyFont: '"Work Sans", system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=Work+Sans:wght@300;400;500;600;700&display=swap',
      mood: 'clean, trust, teal, contemporary',
    },
    style: {
      name: 'Minimalism',
      keywords: ['teal', 'trust', 'clean', 'white'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#0F766E',
      secondary: '#2DD4BF',
      accent: '#0D9488',
      background: '#FFFFFF',
      surface: '#F0FDFA',
      text: '#134E4A',
      textMuted: '#5B716E',
      textSecondary: '#64748B',
      border: '#CCFBF1',
      categoryActive: '#134E4A',
      categoryIndicator: '#0D9488',
      price: '#134E4A',
      priceOriginal: '#94A3B8',
      priceSale: '#0F766E',
      discountBadgeBg: '#F0FDFA',
      discountBadgeText: '#0F766E',
      coverPlaceholderFrom: '#5EEAD4',
      coverPlaceholderTo: '#0F766E',
      coverScrim: 'linear-gradient(to top, rgba(19, 78, 74, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#134E4A',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#CCFBF1',
      productThumbBg: '#F0FDFA',
    }),
  },

  // ── Editorial / contemporary ─────────────────────────────────────────
  {
    id: 'editorial-ink',
    name: 'Editorial Ink',
    label: 'Editorial',
    description: 'Tinta y oro sobre blanco con Playfair. Editorial gastronómico sin fondo tintado.',
    bestFor: ['Cualquier restaurante', 'Menú con carácter', 'Hospitality'],
    context:
      'Blanco, tinta casi negra y acento oro #A16207 con Playfair Display + Karla. Elegancia de carta impresa sobre lienzo blanco.',
    recommendation:
      'Restaurantes que quieren un look de menú editorial sin paletas de cocina específicas ni fondos de color.',
    designSystemQuery: 'restaurant menu editorial playfair white ink gold',
    typography: {
      headingFont: '"Playfair Display", Georgia, serif',
      bodyFont: 'Karla, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Karla:wght@300;400;500;600;700&family=Playfair+Display:wght@400;500;600;700&display=swap',
      mood: 'restaurant, culinary, elegant, hospitality',
    },
    style: {
      name: 'Liquid Glass',
      keywords: ['editorial', 'ink', 'gold', 'serif', 'white'],
      borderRadius: 'rounded',
      cardRadiusPx: 10,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#1C1917',
      secondary: '#78716C',
      accent: '#A16207',
      background: '#FFFFFF',
      surface: '#FAFAF9',
      text: '#1C1917',
      textMuted: '#57534E',
      textSecondary: '#A8A29E',
      border: '#E7E5E4',
      categoryActive: '#1C1917',
      categoryIndicator: '#A16207',
      price: '#1C1917',
      priceOriginal: '#A8A29E',
      priceSale: '#B45309',
      discountBadgeBg: '#FFFBEB',
      discountBadgeText: '#A16207',
      coverPlaceholderFrom: '#D6D3D1',
      coverPlaceholderTo: '#57534E',
      coverScrim: 'linear-gradient(to top, rgba(28, 25, 23, 0.35), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#1C1917',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F5F5F4',
      productThumbBg: '#F5F5F4',
    }),
  },
  {
    id: 'rose-neutral',
    name: 'Rose Neutral',
    label: 'Rose',
    description: 'Rosa polvo sobre blanco con Lora. Sofisticado, cálido y neutro.',
    bestFor: ['Cualquier restaurante', 'Casual elegante', 'Marcas soft'],
    context:
      'Blanco, rose #E11D48 atenuado en superficies y Lora/Raleway. Neutro con un toque floral — esencial, no temático.',
    recommendation:
      'Marcas con tono suave o menús que quieren calidez sin caer en pastelería o festividades.',
    designSystemQuery: 'dusty rose lora raleway white essential menu',
    typography: {
      headingFont: 'Lora, Georgia, serif',
      bodyFont: 'Raleway, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&family=Raleway:wght@300;400;500;600;700&display=swap',
      mood: 'elegant, warm, soft, refined',
    },
    style: {
      name: 'Organic Biophilic',
      keywords: ['rose', 'neutral', 'serif', 'warm', 'white'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#BE123C',
      secondary: '#FB7185',
      accent: '#E11D48',
      background: '#FFFFFF',
      surface: '#FFF8F8',
      text: '#4C0519',
      textMuted: '#9F1239',
      textSecondary: '#9F1239',
      border: '#FECDD3',
      categoryActive: '#4C0519',
      categoryIndicator: '#E11D48',
      price: '#4C0519',
      priceOriginal: '#A8A29E',
      priceSale: '#BE123C',
      discountBadgeBg: '#FFF1F2',
      discountBadgeText: '#BE123C',
      coverPlaceholderFrom: '#FDA4AF',
      coverPlaceholderTo: '#BE123C',
      coverScrim: 'linear-gradient(to top, rgba(76, 5, 25, 0.3), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#4C0519',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FFE4E6',
      productThumbBg: '#FFF1F2',
    }),
  },
  {
    id: 'graphite-lime',
    name: 'Graphite Lime',
    label: 'Graphite',
    description: 'Grafito + lima CTA sobre blanco con DM Sans. Contemporáneo y de alto contraste.',
    bestFor: ['Cualquier restaurante', 'Urbano', 'Marcas bold'],
    context:
      'Blanco, grafito casi negro y lima #65A30D para CTAs/categorías. DM Sans + Inter — contemporáneo, nítido.',
    recommendation:
      'Marcas urbanas o menús que quieren tipografía geométrica y un acento lima para precios/acciones.',
    designSystemQuery: 'graphite lime dm sans inter white high contrast menu',
    typography: {
      headingFont: '"DM Sans", system-ui, sans-serif',
      bodyFont: 'Inter, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400&family=Inter:wght@300;400;500;600;700&display=swap',
      mood: 'contemporary, bold, clean, high-contrast',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['graphite', 'lime', 'contrast', 'modern', 'white'],
      borderRadius: 'sharp',
      cardRadiusPx: 10,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#18181B',
      secondary: '#71717A',
      accent: '#65A30D',
      background: '#FFFFFF',
      surface: '#FAFAFA',
      text: '#18181B',
      textMuted: '#52525B',
      textSecondary: '#A1A1AA',
      border: '#E4E4E7',
      categoryActive: '#FFFFFF',
      categoryIndicator: '#18181B',
      price: '#18181B',
      priceOriginal: '#A1A1AA',
      priceSale: '#65A30D',
      discountBadgeBg: '#F7FEE7',
      discountBadgeText: '#4D7C0F',
      coverPlaceholderFrom: '#A1A1AA',
      coverPlaceholderTo: '#3F3F46',
      coverScrim: 'linear-gradient(to top, rgba(24, 24, 27, 0.35), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#18181B',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F4F4F5',
      productThumbBg: '#F4F4F5',
    }),
  },
  {
    id: 'copper-modern',
    name: 'Copper Modern',
    label: 'Copper',
    description: 'Cobre cálido sobre blanco con Manrope. Contemporáneo y apetitoso.',
    bestFor: ['Cualquier restaurante', 'Casual premium', 'Hospitality'],
    context:
      'Blanco, cobre #C2410C y Manrope/Source Sans 3. Calidez metálica moderna — esencial con personalidad.',
    recommendation:
      'Restaurantes que buscan un acento cálido distinto al rojo clásico, con tipografía contemporánea.',
    designSystemQuery: 'copper modern manrope white restaurant menu',
    typography: {
      headingFont: 'Manrope, system-ui, sans-serif',
      bodyFont: '"Source Sans 3", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Source+Sans+3:wght@300;400;500;600;700&display=swap',
      mood: 'warm, modern, copper, hospitality',
    },
    style: {
      name: 'Minimalism',
      keywords: ['copper', 'warm', 'modern', 'white'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#C2410C',
      secondary: '#FB923C',
      accent: '#EA580C',
      background: '#FFFFFF',
      surface: '#FFF7ED',
      text: '#431407',
      textMuted: '#9A3412',
      textSecondary: '#78716C',
      border: '#FFEDD5',
      categoryActive: '#431407',
      categoryIndicator: '#C2410C',
      price: '#431407',
      priceOriginal: '#A8A29E',
      priceSale: '#C2410C',
      discountBadgeBg: '#FFF7ED',
      discountBadgeText: '#9A3412',
      coverPlaceholderFrom: '#FDBA74',
      coverPlaceholderTo: '#C2410C',
      coverScrim: 'linear-gradient(to top, rgba(67, 20, 7, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#431407',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FFEDD5',
      productThumbBg: '#FFF7ED',
    }),
  }
];
