import type { DigitalMenuTheme, DigitalMenuThemeColors } from './types';

function c(
  colors: Omit<
    DigitalMenuThemeColors,
    'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
  > &
    Partial<
      Pick<
        DigitalMenuThemeColors,
        'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
      >
    >,
): DigitalMenuThemeColors {
  return {
    ...colors,
    priceOriginal: colors.priceOriginal ?? colors.textSecondary,
    priceSale: colors.priceSale ?? colors.primary,
    discountBadgeBg: colors.discountBadgeBg ?? '#141414',
    discountBadgeText: colors.discountBadgeText ?? colors.accent,
  };
}

const BLACK = '#000000';
const SURFACE = '#0A0A0A';
const BORDER = '#1A1A1A';

/**
 * Pure-black background themes (ui-ux-pro-max: photography studio / luxury noir palettes).
 * background is always #000000; surfaces stay near-black for depth without breaking the void look.
 */
export const DARK_DIGITAL_MENU_THEMES: DigitalMenuTheme[] = [
  {
    id: 'obsidiana-oro',
    name: 'Obsidiana Oro',
    label: 'Obsidiana',
    description:
      'Negro absoluto con oro premium — steakhouse, fine dining y menús de alta cocina nocturna.',
    bestFor: ['Fine dining', 'Steakhouse', 'Bar premium'],
    context:
      'Negro absoluto con oro premium y serif Playfair SC. Lujo noir — como un menú de steakhouse de alta gama a la luz de velas.',
    recommendation:
      'Fine dining nocturno, steakhouse premium, bar de alta cocina, menús con cortes exclusivos, maridajes y experiencias íntimas.',
    designSystemQuery: 'luxury restaurant black gold premium menu dark',
    typography: {
      headingFont: '"Playfair Display SC", Georgia, serif',
      bodyFont: 'Karla, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Karla:wght@300;400;500;600;700&family=Playfair+Display+SC:wght@400;700&display=swap',
      mood: 'luxury, noir, gold, culinary, premium',
    },
    style: {
      name: 'Liquid Glass',
      keywords: ['black', 'gold', 'luxury', 'noir'],
      borderRadius: 'rounded',
      cardRadiusPx: 10,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#D4AF37',
      secondary: '#A68A2A',
      accent: '#F5D061',
      background: BLACK,
      surface: SURFACE,
      text: '#FAFAFA',
      textMuted: '#D4D4D4',
      textSecondary: '#A3A3A3',
      border: BORDER,
      categoryActive: '#D4AF37',
      categoryIndicator: '#D4AF37',
      price: '#FAFAFA',
      priceSale: '#F5D061',
      coverPlaceholderFrom: '#3D3520',
      coverPlaceholderTo: BLACK,
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.75), transparent)',
      floatButtonBg: 'rgba(10, 10, 10, 0.94)',
      floatButtonText: '#FAFAFA',
      logoBorder: SURFACE,
      logoPlaceholderBg: '#1F1F1F',
      productThumbBg: '#141414',
    }),
  },
  {
    id: 'neon-tokyo',
    name: 'Neon Tokyo',
    label: 'Tokyo',
    description:
      'Negro total con cian eléctrico y magenta — ramen, izakaya y street food japonés nocturno.',
    bestFor: ['Ramen', 'Izakaya', 'Sushi bar nocturno'],
    context:
      'Negro total con cian eléctrico y magenta cyberpunk. Shinjuku de noche — neones, ramen de madrugada y estética anime urbana.',
    recommendation:
      'Ramen nocturno, izakaya, sushi bar de noche, street food japonés y menús con ambiente cyberpunk o juvenil.',
    designSystemQuery: 'japanese neon tokyo night cyber menu dark',
    typography: {
      headingFont: '"Noto Sans JP", system-ui, sans-serif',
      bodyFont: '"Noto Sans JP", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500;700&display=swap',
      mood: 'cyberpunk, neon, tokyo, electric',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['neon', 'cyber', 'cyan', 'magenta'],
      borderRadius: 'sharp',
      cardRadiusPx: 8,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#00F0FF',
      secondary: '#FF00AA',
      accent: '#FF00AA',
      background: BLACK,
      surface: SURFACE,
      text: '#F0FDFF',
      textMuted: '#A5F3FC',
      textSecondary: '#67E8F9',
      border: '#164E63',
      categoryActive: '#F0FDFF',
      categoryIndicator: '#00F0FF',
      price: '#00F0FF',
      priceSale: '#FF00AA',
      coverPlaceholderFrom: '#083344',
      coverPlaceholderTo: BLACK,
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.8), transparent)',
      floatButtonBg: 'rgba(10, 10, 10, 0.94)',
      floatButtonText: '#F0FDFF',
      logoBorder: SURFACE,
      logoPlaceholderBg: '#0C4A6E',
      productThumbBg: '#082F49',
    }),
  },
  {
    id: 'carbon-bbq',
    name: 'Carbon BBQ',
    label: 'Carbon',
    description:
      'Humo y brasas sobre negro puro — BBQ, parrilla y smokehouse con acentos ámbar encendidos.',
    bestFor: ['BBQ', 'Smokehouse', 'Parrilla americana'],
    context:
      'Humo y brasas sobre negro puro con Bebas Neue bold. Parrilla americana en la oscuridad — brasas rojas y aroma a madera quemada.',
    recommendation:
      'BBQ nocturno, smokehouse, parrilla americana, menús con brisket, ribs ahumadas y sides clásicos en ambiente oscuro.',
    designSystemQuery: 'bbq smokehouse dark ember black menu',
    typography: {
      headingFont: '"Bebas Neue", system-ui, sans-serif',
      bodyFont: 'Barlow, system-ui, sans-serif',
      headingWeight: 400,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Barlow:wght@300;400;500;600;700&family=Bebas+Neue&display=swap',
      mood: 'smoky, bold, ember, masculine',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['ember', 'smoke', 'orange', 'bold'],
      borderRadius: 'sharp',
      cardRadiusPx: 10,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#FF6B00',
      secondary: '#FFAA00',
      accent: '#FFAA00',
      background: BLACK,
      surface: SURFACE,
      text: '#FFF7ED',
      textMuted: '#FED7AA',
      textSecondary: '#FDBA74',
      border: '#431407',
      categoryActive: '#FFAA00',
      categoryIndicator: '#FF6B00',
      price: '#FFF7ED',
      priceSale: '#FFAA00',
      coverPlaceholderFrom: '#7C2D12',
      coverPlaceholderTo: BLACK,
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.78), transparent)',
      floatButtonBg: 'rgba(10, 10, 10, 0.94)',
      floatButtonText: '#FFF7ED',
      logoBorder: SURFACE,
      logoPlaceholderBg: '#292524',
      productThumbBg: '#1C1917',
    }),
  },
  {
    id: 'midnight-taco',
    name: 'Midnight Taco',
    label: 'Midnight',
    description:
      'Taquería nocturna: negro absoluto con rosa neón y lima eléctrica — antojitos después del sunset.',
    bestFor: ['Taquería nocturna', 'Antojitos', 'Food truck'],
    context:
      'Taquería nocturna con rosa neón y lima eléctrica sobre negro. Antojitos después del sunset — tacos de madrugada con actitud.',
    recommendation:
      'Taquería nocturna, antojitos de madrugada, food trucks mexicanos nocturnos, menús con tacos, volcanes y bebidas frías.',
    designSystemQuery: 'mexican taqueria neon dark night',
    typography: {
      headingFont: 'Fredoka, system-ui, sans-serif',
      bodyFont: 'Nunito, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Nunito:wght@300;400;500;600;700&display=swap',
      mood: 'playful, neon, nightlife, street',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['neon', 'lime', 'pink', 'night'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#FF2D6A',
      secondary: '#CCFF00',
      accent: '#CCFF00',
      background: BLACK,
      surface: SURFACE,
      text: '#FFF1F2',
      textMuted: '#FDA4AF',
      textSecondary: '#FB7185',
      border: '#4C0519',
      categoryActive: '#CCFF00',
      categoryIndicator: '#FF2D6A',
      price: '#CCFF00',
      priceSale: '#FF2D6A',
      coverPlaceholderFrom: '#881337',
      coverPlaceholderTo: BLACK,
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.8), transparent)',
      floatButtonBg: 'rgba(10, 10, 10, 0.94)',
      floatButtonText: '#FFF1F2',
      logoBorder: SURFACE,
      logoPlaceholderBg: '#3F0D1A',
      productThumbBg: '#1A0510',
    }),
  },
  {
    id: 'void-omakase',
    name: 'Void Omakase',
    label: 'Omakase',
    description:
      'Omakase minimalista: negro total, oro tenue y jade neón — experiencia íntima y exclusiva.',
    bestFor: ['Omakase', 'Sushi bar', 'Chef table'],
    context:
      'Omakase minimalista: negro total, oro tenue y jade neón. Experiencia íntima y exclusiva — pocos asientos, chef protagonista.',
    recommendation:
      'Omakase, sushi bar premium, chef table, menús degustación japoneses con pocos platos curados y precio por persona.',
    designSystemQuery: 'omakase sushi black minimal gold',
    typography: {
      headingFont: '"Noto Serif JP", Georgia, serif',
      bodyFont: '"Noto Sans JP", system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500;700&family=Noto+Serif+JP:wght@400;500;600;700&display=swap',
      mood: 'minimal, intimate, luxury, japanese',
    },
    style: {
      name: 'Liquid Glass',
      keywords: ['minimal', 'black', 'gold', 'jade'],
      borderRadius: 'rounded',
      cardRadiusPx: 8,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#C9A227',
      secondary: '#4DFF88',
      accent: '#4DFF88',
      background: BLACK,
      surface: SURFACE,
      text: '#F5F5F4',
      textMuted: '#D6D3D1',
      textSecondary: '#A8A29E',
      border: BORDER,
      categoryActive: '#C9A227',
      categoryIndicator: '#C9A227',
      price: '#F5F5F4',
      priceSale: '#4DFF88',
      coverPlaceholderFrom: '#292524',
      coverPlaceholderTo: BLACK,
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.82), transparent)',
      floatButtonBg: 'rgba(10, 10, 10, 0.94)',
      floatButtonText: '#F5F5F4',
      logoBorder: SURFACE,
      logoPlaceholderBg: '#1C1917',
      productThumbBg: '#141414',
    }),
  },
  {
    id: 'noir-copa',
    name: 'Noir Copa',
    label: 'Noir',
    description:
      'Bar de vinos y coctelería: negro absoluto, burdeos profundo y champagne eléctrico.',
    bestFor: ['Wine bar', 'Coctelería', 'Speakeasy'],
    context:
      'Bar de vinos burdeos profundo y champagne eléctrico sobre negro. Speakeasy elegante — copas altas, bajo volumen y ambiente reservado.',
    recommendation:
      'Wine bar, coctelería, speakeasy, menús con vinos por copa, charcutería, ostras y tragos clásicos en ambiente oscuro.',
    designSystemQuery: 'wine bar speakeasy dark burgundy black',
    typography: {
      headingFont: 'Cormorant, Georgia, serif',
      bodyFont: 'Montserrat, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Cormorant:wght@400;500;600;700&family=Montserrat:wght@300;400;500;600;700&display=swap',
      mood: 'noir, wine, speakeasy, refined',
    },
    style: {
      name: 'Liquid Glass',
      keywords: ['burgundy', 'champagne', 'noir', 'elegant'],
      borderRadius: 'rounded',
      cardRadiusPx: 10,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#BE123C',
      secondary: '#FFD54F',
      accent: '#FFD54F',
      background: BLACK,
      surface: SURFACE,
      text: '#FAFAFA',
      textMuted: '#FECDD3',
      textSecondary: '#FDA4AF',
      border: '#4C0519',
      categoryActive: '#FFD54F',
      categoryIndicator: '#BE123C',
      price: '#FAFAFA',
      priceSale: '#FFD54F',
      coverPlaceholderFrom: '#4C0519',
      coverPlaceholderTo: BLACK,
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.8), transparent)',
      floatButtonBg: 'rgba(10, 10, 10, 0.94)',
      floatButtonText: '#FAFAFA',
      logoBorder: SURFACE,
      logoPlaceholderBg: '#3F0D1A',
      productThumbBg: '#1A0510',
    }),
  },
  {
    id: 'cyber-void',
    name: 'Cyber Void',
    label: 'Cyber',
    description:
      'Street food gamer: negro puro, púrpura ultravioleta y cian láser — mercados nocturnos urbanos.',
    bestFor: ['Street food', 'Night market', 'Burger nocturno'],
    context:
      'Street food gamer: negro puro, púrpura ultravioleta y cian láser. Mercado nocturno urbano con energía de e-sports y neones.',
    recommendation:
      'Street food nocturno, burgers de madrugada, night markets urbanos y menús juveniles con promos gaming o eventos.',
    designSystemQuery: 'gaming neon purple cyber street food dark',
    typography: {
      headingFont: '"Lexend Mega", system-ui, sans-serif',
      bodyFont: 'Public Sans, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Lexend+Mega:wght@400;600;700&family=Public+Sans:wght@300;400;500;600;700&display=swap',
      mood: 'cyber, gaming, neon, urban',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['cyber', 'purple', 'cyan', 'neon'],
      borderRadius: 'sharp',
      cardRadiusPx: 8,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#A855F7',
      secondary: '#22D3EE',
      accent: '#22D3EE',
      background: BLACK,
      surface: SURFACE,
      text: '#F5F3FF',
      textMuted: '#DDD6FE',
      textSecondary: '#C4B5FD',
      border: '#3B0764',
      categoryActive: '#F5F3FF',
      categoryIndicator: '#A855F7',
      price: '#22D3EE',
      priceSale: '#F472B6',
      coverPlaceholderFrom: '#4C1D95',
      coverPlaceholderTo: BLACK,
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.82), transparent)',
      floatButtonBg: 'rgba(10, 10, 10, 0.94)',
      floatButtonText: '#F5F3FF',
      logoBorder: SURFACE,
      logoPlaceholderBg: '#2E1065',
      productThumbBg: '#1E1B4B',
    }),
  },
  {
    id: 'lampara-ramen',
    name: 'Lámpara Ramen',
    label: 'Lámpara',
    description:
      'Ramen de madrugada: negro total, rojo linterna y amarillo caldo neón — calidez en la oscuridad.',
    bestFor: ['Ramen', 'Udon', 'Comida caliente nocturna'],
    context:
      'Ramen de madrugada con rojo linterna y amarillo caldo neón sobre negro. Calidez de izakaya a las 2am — humeante y reconfortante.',
    recommendation:
      'Ramen nocturno, udon, comida caliente de madrugada, menús con caldos, gyoza y cerveza japonesa.',
    designSystemQuery: 'ramen izakaya red lantern dark black',
    typography: {
      headingFont: '"Noto Serif JP", Georgia, serif',
      bodyFont: '"Noto Sans JP", system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500;700&family=Noto+Serif+JP:wght@400;500;600;700&display=swap',
      mood: 'warm, lantern, night, brothy',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['lantern', 'red', 'yellow', 'night'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#EF4444',
      secondary: '#FFEE00',
      accent: '#FFEE00',
      background: BLACK,
      surface: SURFACE,
      text: '#FEF2F2',
      textMuted: '#FECACA',
      textSecondary: '#FCA5A5',
      border: '#450A0A',
      categoryActive: '#FFEE00',
      categoryIndicator: '#EF4444',
      price: '#FFEE00',
      priceSale: '#EF4444',
      coverPlaceholderFrom: '#7F1D1D',
      coverPlaceholderTo: BLACK,
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.8), transparent)',
      floatButtonBg: 'rgba(10, 10, 10, 0.94)',
      floatButtonText: '#FEF2F2',
      logoBorder: SURFACE,
      logoPlaceholderBg: '#450A0A',
      productThumbBg: '#1A0505',
    }),
  },
  {
    id: 'abisal-mar',
    name: 'Abisal Mar',
    label: 'Abisal',
    description:
      'Mariscos de profundidad: negro absoluto con turquesa bioluminiscente — ceviche, ostiones y barra cruda nocturna.',
    bestFor: ['Mariscos', 'Cevichería', 'Raw bar'],
    context:
      'Mariscos de profundidad: negro absoluto con turquesa bioluminiscente. Océano abisal — crudo elegante bajo luz tenue.',
    recommendation:
      'Mariscos premium nocturnos, cevichería de autor, raw bar, menús con ostiones, tiraditos y pescado del día en ambiente oscuro.',
    designSystemQuery: 'seafood ocean bioluminescent dark black menu',
    typography: {
      headingFont: '"Playfair Display SC", Georgia, serif',
      bodyFont: 'Karla, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Karla:wght@300;400;500;600;700&family=Playfair+Display+SC:wght@400;700&display=swap',
      mood: 'oceanic, deep, elegant, coastal',
    },
    style: {
      name: 'Liquid Glass',
      keywords: ['ocean', 'turquoise', 'deep', 'noir'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#00FFD0',
      secondary: '#0891B2',
      accent: '#00FFD0',
      background: BLACK,
      surface: SURFACE,
      text: '#ECFEFF',
      textMuted: '#A5F3FC',
      textSecondary: '#67E8F9',
      border: '#164E63',
      categoryActive: '#00FFD0',
      categoryIndicator: '#00FFD0',
      price: '#00FFD0',
      priceSale: '#22D3EE',
      coverPlaceholderFrom: '#0E7490',
      coverPlaceholderTo: BLACK,
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.82), transparent)',
      floatButtonBg: 'rgba(10, 10, 10, 0.94)',
      floatButtonText: '#ECFEFF',
      logoBorder: SURFACE,
      logoPlaceholderBg: '#083344',
      productThumbBg: '#042F2E',
    }),
  },
  {
    id: 'forno-notte',
    name: 'Forno Notte',
    label: 'Forno',
    description:
      'Pizzería nocturna: negro total, rojo tomate ardiente y verde albahaca neón — horno italiano después del anochecer.',
    bestFor: ['Pizzería', 'Trattoria', 'Pasta nocturna'],
    context:
      'Pizzería nocturna: negro total, rojo tomate ardiente y verde albahaca neón. Horno italiano después del anochecer — pizza al carbón.',
    recommendation:
      'Pizzería nocturna, trattoria de cena, pasta y pizza después de las 8pm, menús con horno de leña y vino tinto.',
    designSystemQuery: 'italian pizzeria dark night tomato neon',
    typography: {
      headingFont: '"Playfair Display SC", Georgia, serif',
      bodyFont: 'Lato, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Playfair+Display+SC:wght@400;700&display=swap',
      mood: 'italian, rustic, night, warm',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['tomato', 'basil', 'italian', 'night'],
      borderRadius: 'rounded',
      cardRadiusPx: 14,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#EF4444',
      secondary: '#4ADE80',
      accent: '#4ADE80',
      background: BLACK,
      surface: SURFACE,
      text: '#FEF2F2',
      textMuted: '#FECACA',
      textSecondary: '#FCA5A5',
      border: '#450A0A',
      categoryActive: '#4ADE80',
      categoryIndicator: '#EF4444',
      price: '#4ADE80',
      priceSale: '#EF4444',
      coverPlaceholderFrom: '#7F1D1D',
      coverPlaceholderTo: BLACK,
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.8), transparent)',
      floatButtonBg: 'rgba(10, 10, 10, 0.94)',
      floatButtonText: '#FEF2F2',
      logoBorder: SURFACE,
      logoPlaceholderBg: '#3F0D1A',
      productThumbBg: '#1A0505',
    }),
  },
  {
    id: 'subway-nocturno',
    name: 'Subway Nocturno',
    label: 'Subway',
    description:
      'Estilo sandwich chain sobre negro puro: verde Subway vibrante y amarillo dorado — subs, wraps y bowls personalizables.',
    bestFor: ['Sandwiches', 'Subs', 'Fast casual saludable', 'Wraps y bowls'],
    context:
      'Negro absoluto con verde Subway (#009639) y acento neón (#22C55E) sobre tipografía Bebas Neue bold. Energía de cadena de subs nocturna — fresco, rápido y con contraste alto.',
    recommendation:
      'Cadenas de subs, sandwich shops, menús build-your-own, wraps, ensaladas en bowl, opciones saludables y combos de comida rápida con personalización.',
    designSystemQuery: 'subway sandwich fast food green dark mode vibrant block',
    typography: {
      headingFont: '"Bebas Neue", system-ui, sans-serif',
      bodyFont: '"Source Sans 3", system-ui, sans-serif',
      headingWeight: 400,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Source+Sans+3:wght@300;400;500;600;700&display=swap',
      mood: 'bold, fresh, energetic, fast casual, sandwich',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['subway', 'green', 'bold', 'fast casual', 'dark'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#009639',
      secondary: '#FFC629',
      accent: '#22C55E',
      background: BLACK,
      surface: SURFACE,
      text: '#F8FAFC',
      textMuted: '#86EFAC',
      textSecondary: '#4ADE80',
      border: '#14532D',
      categoryActive: '#22C55E',
      categoryIndicator: '#009639',
      price: '#4ADE80',
      priceSale: '#FFC629',
      discountBadgeBg: '#14532D',
      discountBadgeText: '#FFC629',
      coverPlaceholderFrom: '#14532D',
      coverPlaceholderTo: BLACK,
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.78), transparent)',
      floatButtonBg: 'rgba(10, 10, 10, 0.94)',
      floatButtonText: '#F8FAFC',
      logoBorder: SURFACE,
      logoPlaceholderBg: '#0D1F12',
      productThumbBg: '#0A1A0F',
    }),
  },
];
