import type { DigitalMenuTheme, DigitalMenuThemeColors } from './types';

function c(
  colors: Omit<
    DigitalMenuThemeColors,
    'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
  > &
    Partial<
      Pick<
        DigitalMenuThemeColors,
        'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
      >
    >,
): DigitalMenuThemeColors {
  return {
    ...colors,
    priceOriginal: colors.priceOriginal ?? colors.textSecondary,
    priceSale: colors.priceSale ?? colors.primary,
    discountBadgeBg: colors.discountBadgeBg ?? colors.background,
    discountBadgeText: colors.discountBadgeText ?? colors.primary,
  };
}

/**
 * Temas de festividades mexicanas y eventos especiales.
 * Generados con ui-ux-pro-max (--design-system + domain color/typography/style),
 * paletas ajustadas a la identidad cultural de cada celebración.
 */
export const FESTIVIDADES_MX_THEMES: DigitalMenuTheme[] = [
  {
    id: 'septiembre-patrio',
    name: 'Septiembre Patrio',
    label: 'Patrio',
    description: 'Verde, blanco y rojo de la bandera — mes de la independencia (15-16 sep).',
    bestFor: ['Septiembre', 'Fiestas patrias', 'Menú especial 16 de sep'],
    designSystemQuery: 'mexico independence day september patriotic green white red',
    typography: {
      headingFont: 'Oswald, system-ui, sans-serif',
      bodyFont: 'Montserrat, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&family=Oswald:wght@400;500;600;700&display=swap',
      mood: 'patriotic, bold, festive, mexican',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['patriotic', 'tricolor', 'bold', 'fiesta'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#006847',
      secondary: '#CE1126',
      accent: '#CE1126',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textMuted: '#475569',
      textSecondary: '#64748B',
      border: '#E2E8F0',
      categoryActive: '#006847',
      categoryIndicator: '#CE1126',
      price: '#1A1A1A',
      coverPlaceholderFrom: '#34D399',
      coverPlaceholderTo: '#006847',
      coverScrim: 'linear-gradient(to top, rgba(0, 104, 71, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#006847',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#ECFDF5',
      productThumbBg: '#F0FDF4',
    }),
  },
  {
    id: 'grito-independencia',
    name: 'Grito de Independencia',
    label: 'Grito',
    description: 'Noche del 15 de septiembre: verde profundo, rojo y oro en ambiente nocturno.',
    bestFor: ['Noche del Grito', '15-16 sep', 'Celebración nocturna'],
    designSystemQuery: 'mexico independence night celebration festive dark',
    typography: {
      headingFont: '"Lexend Mega", system-ui, sans-serif',
      bodyFont: '"Public Sans", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Lexend+Mega:wght@400;600;700&family=Public+Sans:wght@300;400;500;600;700&display=swap',
      mood: 'bold, neubrutalist, loud, celebratory',
    },
    style: {
      name: 'Neubrutalist Bold',
      keywords: ['night', 'grito', 'gold', 'patriotic'],
      borderRadius: 'sharp',
      cardRadiusPx: 10,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#FFD700',
      secondary: '#CE1126',
      accent: '#CE1126',
      background: '#0A1F14',
      surface: '#0F2E1C',
      text: '#F5F5F5',
      textMuted: '#D4D4D4',
      textSecondary: '#A3A3A3',
      border: '#1A4D2E',
      categoryActive: '#FFD700',
      categoryIndicator: '#CE1126',
      price: '#F5F5F5',
      coverPlaceholderFrom: '#006847',
      coverPlaceholderTo: '#0A1F14',
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.55), transparent)',
      floatButtonBg: 'rgba(15, 46, 28, 0.92)',
      floatButtonText: '#FFD700',
      logoBorder: '#0F2E1C',
      logoPlaceholderBg: '#1A4D2E',
      productThumbBg: '#1A4D2E',
    }),
  },
  {
    id: 'dia-muertos',
    name: 'Día de Muertos',
    label: 'Muertos',
    description: 'Naranja cempasúchil, morado y rosa — ofrenda y papel picado.',
    bestFor: ['1-2 Nov', 'Día de Muertos', 'Ofrendas y pan de muerto'],
    designSystemQuery: 'day of the dead dia de muertos mexico',
    typography: {
      headingFont: '"Alfa Slab One", Georgia, serif',
      bodyFont: 'Nunito, system-ui, sans-serif',
      headingWeight: 400,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Alfa+Slab+One&family=Nunito:wght@300;400;500;600;700&display=swap',
      mood: 'festive, cultural, bold, warm',
    },
    style: {
      name: 'Glassmorphism',
      keywords: ['marigold', 'purple', 'ofrenda', 'cultural'],
      borderRadius: 'soft',
      cardRadiusPx: 16,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#7B2CBF',
      secondary: '#FF7500',
      accent: '#FF006E',
      background: '#FFF5EB',
      surface: '#FFFFFF',
      text: '#4A1259',
      textMuted: '#6B21A8',
      textSecondary: '#9333EA',
      border: '#F3E8FF',
      categoryActive: '#7B2CBF',
      categoryIndicator: '#FF7500',
      price: '#4A1259',
      coverPlaceholderFrom: '#FF9E00',
      coverPlaceholderTo: '#7B2CBF',
      coverScrim: 'linear-gradient(to top, rgba(74, 18, 89, 0.35), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.93)',
      floatButtonText: '#7B2CBF',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FEF3C7',
      productThumbBg: '#FAE8FF',
    }),
  },
  {
    id: 'mundial-2026',
    name: 'Mundial 2026',
    label: 'Mundial',
    description: 'Verde cancha, oro y tricolor — Copa del Mundo en México.',
    bestFor: ['World Cup 2026', 'Promos deportivas', 'Ver partidos en el local'],
    designSystemQuery: 'mexico world cup 2026 football soccer',
    typography: {
      headingFont: '"Barlow Condensed", system-ui, sans-serif',
      bodyFont: 'Barlow, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Barlow+Condensed:wght@400;500;600;700&family=Barlow:wght@300;400;500;600;700&display=swap',
      mood: 'sports, energetic, bold, competitive',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['soccer', 'world cup', 'stadium', 'energy'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#006847',
      secondary: '#228B22',
      accent: '#FFD700',
      background: '#F0FDF4',
      surface: '#FFFFFF',
      text: '#14532D',
      textMuted: '#166534',
      textSecondary: '#15803D',
      border: '#BBF7D0',
      categoryActive: '#FFFFFF',
      categoryIndicator: '#006847',
      price: '#14532D',
      coverPlaceholderFrom: '#4ADE80',
      coverPlaceholderTo: '#006847',
      coverScrim: 'linear-gradient(to top, rgba(20, 83, 45, 0.35), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#006847',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#DCFCE7',
      productThumbBg: '#DCFCE7',
    }),
  },
  {
    id: 'navidad-posadas',
    name: 'Navidad Posadas',
    label: 'Navidad',
    description: 'Rojo posada, verde pino y dorado — diciembre mexicano.',
    bestFor: ['Navidad', 'Posadas', 'Cena de fin de año'],
    designSystemQuery: 'mexican christmas navidad posada',
    typography: {
      headingFont: '"Playfair Display", Georgia, serif',
      bodyFont: 'Lato, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Playfair+Display:wght@400;500;600;700&display=swap',
      mood: 'warm, elegant, holiday, inviting',
    },
    style: {
      name: 'Glassmorphism',
      keywords: ['christmas', 'posada', 'warm', 'gold'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#B91C1C',
      secondary: '#165B33',
      accent: '#D4AF37',
      background: '#FFFBF5',
      surface: '#FFFFFF',
      text: '#450A0A',
      textMuted: '#7F1D1D',
      textSecondary: '#991B1B',
      border: '#FECACA',
      categoryActive: '#B91C1C',
      categoryIndicator: '#165B33',
      price: '#450A0A',
      coverPlaceholderFrom: '#FCA5A5',
      coverPlaceholderTo: '#165B33',
      coverScrim: 'linear-gradient(to top, rgba(69, 10, 10, 0.3), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#B91C1C',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FEE2E2',
      productThumbBg: '#F0FDF4',
    }),
  },
  {
    id: 'cinco-mayo',
    name: 'Cinco de Mayo',
    label: '5 Mayo',
    description: 'Tricolor festivo con verde, rojo y oro — batalla de Puebla.',
    bestFor: ['5 de Mayo', 'Promos Puebla', 'Fiesta mexicana'],
    designSystemQuery: 'cinco de mayo mexico festive',
    typography: {
      headingFont: 'Fredoka, system-ui, sans-serif',
      bodyFont: 'Nunito, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Nunito:wght@300;400;500;600;700&display=swap',
      mood: 'playful, festive, warm, approachable',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['fiesta', 'papel picado', 'colorful', 'celebration'],
      borderRadius: 'soft',
      cardRadiusPx: 16,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#006847',
      secondary: '#E63946',
      accent: '#FFB703',
      background: '#FFF8E7',
      surface: '#FFFFFF',
      text: '#1A1A1A',
      textMuted: '#475569',
      textSecondary: '#64748B',
      border: '#FDE68A',
      categoryActive: '#006847',
      categoryIndicator: '#E63946',
      price: '#1A1A1A',
      coverPlaceholderFrom: '#FFD60A',
      coverPlaceholderTo: '#006847',
      coverScrim: 'linear-gradient(to top, rgba(0, 104, 71, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.93)',
      floatButtonText: '#006847',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#ECFDF5',
      productThumbBg: '#FEF3C7',
    }),
  },
  {
    id: 'revolucion-mx',
    name: 'Revolución Mexicana',
    label: 'Revolución',
    description: 'Tierra, verde oliva y oro viejo — 20 de noviembre.',
    bestFor: ['20 de Nov', 'Revolución mexicana', 'Cocina tradicional'],
    designSystemQuery: 'revolucion mexicana november',
    typography: {
      headingFont: '"EB Garamond", Georgia, serif',
      bodyFont: '"Source Sans 3", system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=EB+Garamond:wght@500;600;700&family=Source+Sans+3:wght@300;400;500;600;700&display=swap',
      mood: 'historical, warm, traditional, dignified',
    },
    style: {
      name: 'Organic Biophilic',
      keywords: ['historical', 'earth', 'tradition', 'rustic'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#6B4423',
      secondary: '#2D4A22',
      accent: '#C5A059',
      background: '#F5F0E8',
      surface: '#FFFFFF',
      text: '#3D2914',
      textMuted: '#57534E',
      textSecondary: '#78716C',
      border: '#E7E5E4',
      categoryActive: '#6B4423',
      categoryIndicator: '#2D4A22',
      price: '#3D2914',
      coverPlaceholderFrom: '#A68A64',
      coverPlaceholderTo: '#6B4423',
      coverScrim: 'linear-gradient(to top, rgba(61, 41, 20, 0.35), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#6B4423',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#EDE4D4',
      productThumbBg: '#EDE4D4',
    }),
  },
];
