import type { DigitalMenuTheme, DigitalMenuThemeColors } from './types';

function c(
  colors: Omit<
    DigitalMenuThemeColors,
    'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
  > &
    Partial<
      Pick<
        DigitalMenuThemeColors,
        'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
      >
    >,
): DigitalMenuThemeColors {
  return {
    ...colors,
    priceOriginal: colors.priceOriginal ?? colors.textSecondary,
    priceSale: colors.priceSale ?? colors.primary,
    discountBadgeBg: colors.discountBadgeBg ?? colors.background,
    discountBadgeText: colors.discountBadgeText ?? colors.primary,
  };
}

/** Themes 27–38 — batch 2 via ui-ux-pro-max (--design-system + domain color/typography/style). */
export const EXTENDED_DIGITAL_MENU_THEMES_2: DigitalMenuTheme[] = [
  {
    id: 'dim-sum-china',
    name: 'Dim Sum China',
    label: 'Dim Sum',
    description: 'Rojo imperial y dorado con tipografía china serif + sans.',
    bestFor: ['Dim sum', 'Comida china', 'Noodles y arroz'],
    context:
      'Rojo imperial y dorado con tipografía china Noto Serif SC. Festividad cantonesa, vapor de bamboo y elegancia de salón chino tradicional.',
    recommendation:
      'Dim sum, comida cantonesa, menús con dumplings al vapor, baozi, noodles, arroz frito y té chino.',
    designSystemQuery: 'chinese dim sum restaurant',
    typography: {
      headingFont: '"Noto Serif SC", Georgia, serif',
      bodyFont: '"Noto Sans SC", system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@300;400;500;700&family=Noto+Serif+SC:wght@400;500;600;700&display=swap',
      mood: 'chinese, traditional, elegant, culinary',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['bold', 'red', 'gold', 'festive'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#C41E3A',
      secondary: '#D4AF37',
      accent: '#D4AF37',
      background: '#FFF8F0',
      surface: '#FFFFFF',
      text: '#450A0A',
      textMuted: '#7F1D1D',
      textSecondary: '#991B1B',
      border: '#FECACA',
      categoryActive: '#C41E3A',
      categoryIndicator: '#D4AF37',
      price: '#450A0A',
      coverPlaceholderFrom: '#FCA5A5',
      coverPlaceholderTo: '#C41E3A',
      coverScrim: 'linear-gradient(to top, rgba(69, 10, 10, 0.35), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#450A0A',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FEE2E2',
      productThumbBg: '#FEE2E2',
    }),
  },
  {
    id: 'ceviche-peru',
    name: 'Ceviche Perú',
    label: 'Perú',
    description: 'Azul costero, amarillo cítrico y acentos latinos vibrantes.',
    bestFor: ['Cevichería', 'Comida peruana', 'Anticuchos'],
    context:
      'Azul costero, amarillo cítrico y acentos latinos vibrantes con Libre Baskerville. Frescura peruana, limón ácido y mar en cada plato.',
    recommendation:
      'Cevicherías peruanas, anticuchos, menús con ceviche clásico, tiradito, causa limeña, chicha morada y comida criolla.',
    designSystemQuery: 'peruvian ceviche latin',
    typography: {
      headingFont: '"Libre Baskerville", Georgia, serif',
      bodyFont: '"Open Sans", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Libre+Baskerville:wght@400;700&family=Open+Sans:wght@300;400;500;600;700&display=swap',
      mood: 'latin, coastal, fresh, vibrant',
    },
    style: {
      name: 'Glassmorphism',
      keywords: ['fresh', 'coastal', 'layered', 'bright'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#0EA5E9',
      secondary: '#38BDF8',
      accent: '#FBBF24',
      background: '#F0F9FF',
      surface: '#FFFFFF',
      text: '#0C4A6E',
      textMuted: '#0369A1',
      textSecondary: '#0284C7',
      border: '#BAE6FD',
      categoryActive: '#0C4A6E',
      categoryIndicator: '#0EA5E9',
      price: '#0C4A6E',
      coverPlaceholderFrom: '#7DD3FC',
      coverPlaceholderTo: '#0EA5E9',
      coverScrim: 'linear-gradient(to top, rgba(12, 74, 110, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.93)',
      floatButtonText: '#0C4A6E',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#E0F2FE',
      productThumbBg: '#E0F2FE',
    }),
  },
  {
    id: 'griego-aegeo',
    name: 'Griego Egeo',
    label: 'Griego',
    description: 'Azul aegeo y blanco — taverna mediterránea con glassmorphism.',
    bestFor: ['Taverna griega', 'Gyros', 'Ensalada griega'],
    context:
      'Azul aegeo y blanco puro con Literata clásica. Taverna griega soleada — columnas, olivos y mesa con vista al mar.',
    recommendation:
      'Tavernas griegas, gyros, ensalada griega, menús con souvlaki, moussaka, tzatziki, feta y vino retsina.',
    designSystemQuery: 'greek taverna aegean',
    typography: {
      headingFont: 'Literata, Georgia, serif',
      bodyFont: '"Open Sans", system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Literata:wght@500;600;700&family=Open+Sans:wght@300;400;500;600;700&display=swap',
      mood: 'mediterranean, clean, airy, classic',
    },
    style: {
      name: 'Glassmorphism',
      keywords: ['blue', 'white', 'aegean', 'fresh'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#1565C0',
      secondary: '#42A5F5',
      accent: '#F97316',
      background: '#EFF6FF',
      surface: '#FFFFFF',
      text: '#1E3A8A',
      textMuted: '#334155',
      textSecondary: '#64748B',
      border: '#BFDBFE',
      categoryActive: '#1565C0',
      categoryIndicator: '#1565C0',
      price: '#1E3A8A',
      coverPlaceholderFrom: '#93C5FD',
      coverPlaceholderTo: '#1565C0',
      coverScrim: 'linear-gradient(to top, rgba(30, 58, 138, 0.3), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#1E3A8A',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#DBEAFE',
      productThumbBg: '#DBEAFE',
    }),
  },
  {
    id: 'pho-saigon',
    name: 'Pho Saigón',
    label: 'Pho',
    description: 'Caldo cálido y tipografía Be Vietnam Pro — fiel al design system vietnamita.',
    bestFor: ['Pho', 'Banh mi', 'Comida vietnamita'],
    context:
      'Caldo cálido ámbar con Be Vietnam Pro — fiel al design system vietnamita. Aroma de anís estrellado, hierbabuena y caldo de hueso largo.',
    recommendation:
      'Pho, banh mi, comida vietnamita, menús con sopas de fideos, rollitos primavera, café con leche condensada y hierbas frescas.',
    designSystemQuery: 'vietnamese pho restaurant',
    typography: {
      headingFont: '"Be Vietnam Pro", system-ui, sans-serif',
      bodyFont: '"Noto Sans", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Be+Vietnam+Pro:wght@300;400;500;600;700&family=Noto+Sans:wght@300;400;500;600;700&display=swap',
      mood: 'vietnamese, international, readable, clean',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['warm', 'broth', 'comfort', 'asian'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#B45309',
      secondary: '#D97706',
      accent: '#DC2626',
      background: '#FFFBEB',
      surface: '#FFFFFF',
      text: '#78350F',
      textMuted: '#92400E',
      textSecondary: '#B45309',
      border: '#FDE68A',
      categoryActive: '#78350F',
      categoryIndicator: '#B45309',
      price: '#78350F',
      coverPlaceholderFrom: '#FCD34D',
      coverPlaceholderTo: '#B45309',
      coverScrim: 'linear-gradient(to top, rgba(120, 53, 15, 0.34), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#78350F',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FEF3C7',
      productThumbBg: '#FEF3C7',
    }),
  },
  {
    id: 'helado-gelato',
    name: 'Helado Gelato',
    label: 'Helado',
    description: 'Pasteles rosa y lavanda — exaggerated minimalism para heladerías.',
    bestFor: ['Heladería', 'Gelato', 'Postres fríos'],
    context:
      'Pasteles rosa y lavanda con Baloo 2 exagerado. Dulce, frío y divertido — como una heladería italiana de colores pastel en verano.',
    recommendation:
      'Heladerías, gelaterías, menús con sabores artesanales, paletas, sundaes, waffles con helado y toppings.',
    designSystemQuery: 'gelato ice cream shop pastel',
    typography: {
      headingFont: '"Baloo 2", cursive',
      bodyFont: 'Quicksand, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 500,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Baloo+2:wght@500;600;700&family=Quicksand:wght@400;500;600;700&display=swap',
      mood: 'playful, sweet, pastel, fun',
    },
    style: {
      name: 'Exaggerated Minimalism',
      keywords: ['pastel', 'sweet', 'soft', 'playful'],
      borderRadius: 'pill',
      cardRadiusPx: 20,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#F472B6',
      secondary: '#C4B5FD',
      accent: '#38BDF8',
      background: '#FDF4FF',
      surface: '#FFFFFF',
      text: '#701A75',
      textMuted: '#86198F',
      textSecondary: '#A21CAF',
      border: '#F5D0FE',
      categoryActive: '#701A75',
      categoryIndicator: '#F472B6',
      price: '#701A75',
      coverPlaceholderFrom: '#FBCFE8',
      coverPlaceholderTo: '#C4B5FD',
      coverScrim: 'linear-gradient(to top, rgba(112, 26, 117, 0.25), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#701A75',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FAE8FF',
      productThumbBg: '#FAE8FF',
    }),
  },
  {
    id: 'cubano-caribe',
    name: 'Cubano Caribe',
    label: 'Cubano',
    description: 'Coral caribeño y azul profundo — sándwiches y cocina tropical.',
    bestFor: ['Cubano', 'Caribe', 'Tropical casual'],
    context:
      'Coral caribeño y azul profundo con Josefin Sans tropical. Sabor de La Habana — ritmo, sol y sándwich cubano crujiente.',
    recommendation:
      'Cocina cubana, caribeña tropical casual, menús con sandwich cubano, ropa vieja, tostones, mojitos y plátanos.',
    designSystemQuery: 'cuban sandwich tropical',
    typography: {
      headingFont: '"Josefin Sans", system-ui, sans-serif',
      bodyFont: '"Work Sans", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Josefin+Sans:wght@400;500;600;700&family=Work+Sans:wght@300;400;500;600;700&display=swap',
      mood: 'tropical, retro, warm, caribbean',
    },
    style: {
      name: 'Glassmorphism',
      keywords: ['tropical', 'coral', 'coastal', 'vibrant'],
      borderRadius: 'soft',
      cardRadiusPx: 16,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#E63946',
      secondary: '#457B9D',
      accent: '#F4A261',
      background: '#F1FAEE',
      surface: '#FFFFFF',
      text: '#1D3557',
      textMuted: '#457B9D',
      textSecondary: '#E63946',
      border: '#A8DADC',
      categoryActive: '#FFFFFF',
      categoryIndicator: '#E63946',
      price: '#1D3557',
      coverPlaceholderFrom: '#F4A261',
      coverPlaceholderTo: '#E63946',
      coverScrim: 'linear-gradient(to top, rgba(29, 53, 87, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#1D3557',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#D8F3DC',
      productThumbBg: '#D8F3DC',
    }),
  },
  {
    id: 'tex-mex-cantina',
    name: 'Tex-Mex Cantina',
    label: 'Tex-Mex',
    description: 'Rosa vibrante y azul engagement — estilo cantina tex-mex.',
    bestFor: ['Tex-Mex', 'Cantina', 'Nachos y fajitas'],
    context:
      'Rosa vibrante y azul engagement con Fredoka festiva. Cantina tex-mex ruidosa — nachos, margaritas y música en el fondo.',
    recommendation:
      'Tex-Mex, cantinas, menús con fajitas, nachos, queso fundido, burritos grandes, margaritas y combos para grupos.',
    designSystemQuery: 'tex mex cantina vibrant',
    typography: {
      headingFont: 'Fredoka, system-ui, sans-serif',
      bodyFont: 'Nunito, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Nunito:wght@300;400;500;600;700&display=swap',
      mood: 'playful, bold, festive, warm',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['rose', 'blue', 'festive', 'bold'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#E11D48',
      secondary: '#FB7185',
      accent: '#2563EB',
      background: '#FFF1F2',
      surface: '#FFFFFF',
      text: '#881337',
      textMuted: '#9F1239',
      textSecondary: '#BE123C',
      border: '#FECDD3',
      categoryActive: '#881337',
      categoryIndicator: '#E11D48',
      price: '#881337',
      coverPlaceholderFrom: '#FDA4AF',
      coverPlaceholderTo: '#E11D48',
      coverScrim: 'linear-gradient(to top, rgba(136, 19, 55, 0.34), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.93)',
      floatButtonText: '#881337',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FFE4E6',
      productThumbBg: '#FFE4E6',
    }),
  },
  {
    id: 'food-truck',
    name: 'Food Truck',
    label: 'Truck',
    description: 'Amarillo llamativo y rojo urbano — food truck callejero.',
    bestFor: ['Food truck', 'Street food diurno', 'Festival'],
    context:
      'Amarillo llamativo y rojo urbano con Archivo Black bold. Food truck de festival — colores que gritan desde la calle y menú corto pero impactante.',
    recommendation:
      'Food trucks, street food diurno, festivales gastronómicos, menús cortos con 5-10 ítems estrella y promos del día.',
    designSystemQuery: 'food truck urban colorful',
    typography: {
      headingFont: '"Archivo Black", system-ui, sans-serif',
      bodyFont: 'Roboto, system-ui, sans-serif',
      headingWeight: 400,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Archivo+Black&family=Roboto:wght@300;400;500;700&display=swap',
      mood: 'bold, urban, street, energetic',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['yellow', 'red', 'urban', 'street'],
      borderRadius: 'sharp',
      cardRadiusPx: 10,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#FBBF24',
      secondary: '#EF4444',
      accent: '#EF4444',
      background: '#FFFBEB',
      surface: '#FFFFFF',
      text: '#1C1917',
      textMuted: '#44403C',
      textSecondary: '#57534E',
      border: '#FDE68A',
      categoryActive: '#1C1917',
      categoryIndicator: '#EF4444',
      price: '#1C1917',
      coverPlaceholderFrom: '#FDE047',
      coverPlaceholderTo: '#FBBF24',
      coverScrim: 'linear-gradient(to top, rgba(28, 25, 23, 0.35), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#1C1917',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FEF3C7',
      productThumbBg: '#FEF3C7',
    }),
  },
  {
    id: 'granja-organica',
    name: 'Granja Orgánica',
    label: 'Granja',
    description: 'Farm-to-table con verdes tierra y tipografía Lora + Raleway (Organic Biophilic).',
    bestFor: ['Farm-to-table', 'Orgánico', 'Mercado local'],
    context:
      'Verdes tierra y tipografía Lora/Raleway orgánica. Farm-to-table honesto — del campo a la mesa, ingredientes de temporada y productores locales.',
    recommendation:
      'Farm-to-table, orgánico, mercados locales, menús de temporada con verduras de huerto, carnes de granja y proveedores nombrados.',
    designSystemQuery: 'farm to table organic',
    typography: {
      headingFont: 'Lora, Georgia, serif',
      bodyFont: 'Raleway, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&family=Raleway:wght@300;400;500;600;700&display=swap',
      mood: 'calm, wellness, natural, organic',
    },
    style: {
      name: 'Organic Biophilic',
      keywords: ['farm', 'earth', 'sustainable', 'natural'],
      borderRadius: 'soft',
      cardRadiusPx: 16,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#65A30D',
      secondary: '#A3E635',
      accent: '#CA8A04',
      background: '#FAFAF5',
      surface: '#FFFFFF',
      text: '#365314',
      textMuted: '#4D7C0F',
      textSecondary: '#65A30D',
      border: '#D9F99D',
      categoryActive: '#365314',
      categoryIndicator: '#65A30D',
      price: '#365314',
      coverPlaceholderFrom: '#BEF264',
      coverPlaceholderTo: '#65A30D',
      coverScrim: 'linear-gradient(to top, rgba(54, 83, 20, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#365314',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#ECFCCB',
      productThumbBg: '#ECFCCB',
    }),
  },
  {
    id: 'lounge-nocturno',
    name: 'Lounge Nocturno',
    label: 'Lounge',
    description: 'Oscuro con oro y acentos rojos — bar lounge nocturno.',
    bestFor: ['Bar lounge', 'Coctelería', 'Música en vivo'],
    context:
      'Oscuro con oro y acentos rojos con Cormorant/Montserrat. Bar lounge nocturno — sofás bajos, jazz suave y cocteles de autor.',
    recommendation:
      'Bar lounge, coctelería, música en vivo, menús con botanas premium, tablas para compartir, tragos de autor y ambiente after-office.',
    designSystemQuery: 'night club lounge dark',
    typography: {
      headingFont: 'Cormorant, Georgia, serif',
      bodyFont: 'Montserrat, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Cormorant:wght@400;500;600;700&family=Montserrat:wght@300;400;500;600;700&display=swap',
      mood: 'luxury, nightlife, refined, premium',
    },
    style: {
      name: 'Liquid Glass',
      keywords: ['dark', 'gold', 'nightlife', 'premium'],
      borderRadius: 'rounded',
      cardRadiusPx: 10,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#D4AF37',
      secondary: '#DC2626',
      accent: '#DC2626',
      background: '#0F0F0F',
      surface: '#1A1A1A',
      text: '#F5F5F5',
      textMuted: '#D4D4D4',
      textSecondary: '#A3A3A3',
      border: '#404040',
      categoryActive: '#D4AF37',
      categoryIndicator: '#D4AF37',
      price: '#F5F5F5',
      coverPlaceholderFrom: '#525252',
      coverPlaceholderTo: '#0F0F0F',
      coverScrim: 'linear-gradient(to top, rgba(0, 0, 0, 0.6), transparent)',
      floatButtonBg: 'rgba(26, 26, 26, 0.92)',
      floatButtonText: '#F5F5F5',
      logoBorder: '#1A1A1A',
      logoPlaceholderBg: '#404040',
      productThumbBg: '#404040',
    }),
  },
  {
    id: 'brunch-dorado',
    name: 'Brunch Dorado',
    label: 'Brunch',
    description: 'Naranja mimosa y dorado — brunch de fin de semana.',
    bestFor: ['Brunch', 'Mimosa bar', 'Desayunos gourmet'],
    context:
      'Naranja mimosa y dorado con Playfair Display elegante. Brunch de domingo — mimosas, sol de mañana y mesa larga con amigos.',
    recommendation:
      'Brunch, mimosa bar, desayunos gourmet de fin de semana, menús con eggs benedict, french toast, avocado toast y jugos frescos.',
    designSystemQuery: 'brunch bottomless mimosa',
    typography: {
      headingFont: '"Playfair Display", Georgia, serif',
      bodyFont: 'Lato, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Playfair+Display:wght@400;500;600;700&display=swap',
      mood: 'elegant, warm, weekend, inviting',
    },
    style: {
      name: 'Glassmorphism',
      keywords: ['mimosa', 'orange', 'gold', 'brunch'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#F97316',
      secondary: '#FBBF24',
      accent: '#FDE047',
      background: '#FFFBEB',
      surface: '#FFFFFF',
      text: '#78350F',
      textMuted: '#92400E',
      textSecondary: '#B45309',
      border: '#FDE68A',
      categoryActive: '#78350F',
      categoryIndicator: '#F97316',
      price: '#78350F',
      coverPlaceholderFrom: '#FDBA74',
      coverPlaceholderTo: '#F97316',
      coverScrim: 'linear-gradient(to top, rgba(120, 53, 15, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.93)',
      floatButtonText: '#78350F',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FEF3C7',
      productThumbBg: '#FEF3C7',
    }),
  },
  {
    id: 'libanes-fenix',
    name: 'Libanés Fénix',
    label: 'Libanés',
    description: 'Terracota y oliva con nature distilled — mezze y falafel.',
    bestFor: ['Libanés', 'Mezze', 'Shawarma'],
    context:
      'Terracota y oliva con EB Garamond artesanal. Mezze del Levante — hummus cremoso, pan árabe caliente y especias de Oriente Medio.',
    recommendation:
      'Libanés, mezze, shawarma, menús con falafel, kibbeh, tabbouleh, fatayer y combinados para compartir.',
    designSystemQuery: 'lebanese mezze restaurant',
    typography: {
      headingFont: '"EB Garamond", Georgia, serif',
      bodyFont: '"Source Sans 3", system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=EB+Garamond:wght@500;600;700&family=Source+Sans+3:wght@300;400;500;600;700&display=swap',
      mood: 'artisan, warm, levantine, elegant',
    },
    style: {
      name: 'Organic Biophilic',
      keywords: ['terracotta', 'olive', 'mezze', 'warm'],
      borderRadius: 'rounded',
      cardRadiusPx: 14,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#C45C26',
      secondary: '#2D5016',
      accent: '#CA8A04',
      background: '#FBF7F0',
      surface: '#FFFFFF',
      text: '#5C3D2E',
      textMuted: '#78716C',
      textSecondary: '#92400E',
      border: '#E7D5C4',
      categoryActive: '#5C3D2E',
      categoryIndicator: '#C45C26',
      price: '#5C3D2E',
      coverPlaceholderFrom: '#D4A574',
      coverPlaceholderTo: '#C45C26',
      coverScrim: 'linear-gradient(to top, rgba(92, 61, 46, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#5C3D2E',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F5EDE4',
      productThumbBg: '#F5EDE4',
    }),
  },
];
