import type { DigitalMenuTheme, DigitalMenuThemeColors } from './types';
import { EXTENDED_DIGITAL_MENU_THEMES } from './catalogExtended';
import { EXTENDED_DIGITAL_MENU_THEMES_2 } from './catalogExtended2';
import { FESTIVIDADES_MX_THEMES } from './catalogFestividades';
import { DARK_DIGITAL_MENU_THEMES } from './catalogDark';
import { VENUE_CATEGORY_DIGITAL_MENU_THEMES } from './catalogVenueCategories';

function c(
  colors: Omit<
    DigitalMenuThemeColors,
    'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
  > &
    Partial<
      Pick<
        DigitalMenuThemeColors,
        'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
      >
    >,
): DigitalMenuThemeColors {
  return {
    ...colors,
    priceOriginal: colors.priceOriginal ?? colors.textSecondary,
    priceSale: colors.priceSale ?? colors.primary,
    discountBadgeBg: colors.discountBadgeBg ?? colors.background,
    discountBadgeText: colors.discountBadgeText ?? colors.primary,
  };
}

/**
 * Curated digital menu themes generated with ui-ux-pro-max design-system searches.
 * Each theme combines typography pairing, color roles, surfaces, and layout tokens.
 * Stored in restaurants.digital_menu_theme_id — persisted via PATCH /restaurants/{id}.
 */
export const DIGITAL_MENU_THEMES: DigitalMenuTheme[] = [
  {
    id: 'original',
    name: 'Original',
    label: 'Original',
    description:
      'Aspecto neutro por defecto: blanco, grises slate y tipografía del sistema. El que tenías antes de los temas.',
    bestFor: ['Cualquier restaurante', 'Vista limpia', 'Estilo delivery app'],
    context:
      'Tema neutro y limpio con fondo blanco, grises slate y tipografía del sistema. Sin personalidad fuerte: se siente como una app de delivery genérica, legible y familiar.',
    recommendation:
      'Menús de cualquier tipo cuando quieres máxima claridad sin distraer del contenido. Ideal como punto de partida o si tu marca aún no tiene identidad visual definida.',
    designSystemQuery: 'neutral default (pre-theme hardcoded preview)',
    typography: {
      headingFont:
        'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      bodyFont: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl: '',
      mood: 'neutral, clean, system, minimal',
    },
    style: {
      name: 'Minimal default',
      keywords: ['neutral', 'white', 'slate', 'clean'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#111827',
      secondary: '#64748b',
      accent: '#111827',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748b',
      textSecondary: '#94a3b8',
      border: '#EEF2F7',
      categoryActive: '#111827',
      categoryIndicator: '#111827',
      price: '#111827',
      priceOriginal: '#94a3b8',
      priceSale: '#dc2626',
      discountBadgeBg: '#fef2f2',
      discountBadgeText: '#dc2626',
      coverPlaceholderFrom: '#CBD5E1',
      coverPlaceholderTo: '#94A3B8',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'original-verde',
    name: 'Original Verde',
    label: 'Original+',
    description:
      'Igual que Original, con categorías en verde delivery (#06C167).',
    bestFor: ['Cualquier restaurante', 'Promos', 'Estilo delivery app'],
    context:
      'Igual que Original en estructura, pero con acento verde delivery (#06C167) en categorías activas y promociones. Sensación de app de pedidos moderna tipo Uber Eats o Rappi.',
    recommendation:
      'Restaurantes con delivery activo, dark kitchens, comida rápida o cualquier menú que quiera transmitir agilidad y pedidos en línea sin cambiar mucho el look base.',
    designSystemQuery: 'neutral default + delivery green category accent #06C167',
    typography: {
      headingFont:
        'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      bodyFont: 'system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl: '',
      mood: 'neutral, clean, system, minimal',
    },
    style: {
      name: 'Minimal default',
      keywords: ['neutral', 'white', 'slate', 'mint accent'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#111827',
      secondary: '#64748b',
      accent: '#06C167',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748b',
      textSecondary: '#94a3b8',
      border: '#EEF2F7',
      categoryActive: '#06C167',
      categoryIndicator: '#06C167',
      price: '#111827',
      priceOriginal: '#94a3b8',
      priceSale: '#dc2626',
      discountBadgeBg: '#fef2f2',
      discountBadgeText: '#dc2626',
      coverPlaceholderFrom: '#CBD5E1',
      coverPlaceholderTo: '#94A3B8',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'clasico-rojo',
    name: 'Clásico Rojo',
    label: 'Clásico',
    description:
      'Paleta apetitosa rojo y dorado con tipografía editorial. Ideal como tema base de Venddelo.',
    bestFor: ['Restaurante general', 'Comida casera', 'Menú multigusto'],
    context:
      'Paleta apetitosa rojo carmesí y dorado cálido con tipografía editorial Playfair. Transmite calidez gastronómica, tradición y un toque elegante sin ser pretencioso.',
    recommendation:
      'Restaurantes de comida casera, fondas, cocina mexicana general, marisquerías familiares o cualquier menú multigusto que busque verse apetitoso y confiable.',
    designSystemQuery: 'restaurant food delivery digital menu mobile',
    typography: {
      headingFont: '"Playfair Display SC", Georgia, serif',
      bodyFont: 'Karla, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Karla:wght@300;400;500;600;700&family=Playfair+Display+SC:wght@400;700&display=swap',
      mood: 'restaurant, culinary, elegant, hospitality',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['bold', 'energetic', 'food', 'high contrast'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#DC2626',
      secondary: '#F87171',
      accent: '#CA8A04',
      background: '#FEF2F2',
      surface: '#FFFFFF',
      text: '#450A0A',
      textMuted: '#7F1D1D',
      textSecondary: '#991B1B',
      border: '#FECACA',
      categoryActive: '#450A0A',
      categoryIndicator: '#DC2626',
      price: '#450A0A',
      coverPlaceholderFrom: '#FCA5A5',
      coverPlaceholderTo: '#DC2626',
      coverScrim: 'linear-gradient(to top, rgba(69, 10, 10, 0.35), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#450A0A',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FEE2E2',
      productThumbBg: '#FEE2E2',
    }),
  },
  {
    id: 'taqueria-viva',
    name: 'Taquería Viva',
    label: 'Taquería',
    description:
      'Tonos cálidos y tipografía amigable para tacos, antojitos y cocina mexicana informal.',
    bestFor: ['Taquería', 'Antojitos', 'Food truck mexicano'],
    context:
      'Colores cálidos rosa-rojo y azul vibrante con tipografía redondeada Fredoka/Nunito. Sensación juguetona, callejera y muy mexicana — como un puesto de tacos con personalidad.',
    recommendation:
      'Taquerías, antojerías, fondas de barrio, food trucks mexicanos, tortas, quesadillas y menús con tacos, gringas, al pastor y bebidas aguas frescas.',
    designSystemQuery: 'mexican taqueria vibrant warm',
    typography: {
      headingFont: 'Fredoka, system-ui, sans-serif',
      bodyFont: 'Nunito, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Nunito:wght@300;400;500;600;700&display=swap',
      mood: 'playful, friendly, warm, approachable',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['playful', 'block layout', 'duotone', 'youthful'],
      borderRadius: 'soft',
      cardRadiusPx: 16,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#E11D48',
      secondary: '#FB7185',
      accent: '#2563EB',
      background: '#FFF1F2',
      surface: '#FFFFFF',
      text: '#881337',
      textMuted: '#9F1239',
      textSecondary: '#BE123C',
      border: '#FECDD3',
      categoryActive: '#881337',
      categoryIndicator: '#E11D48',
      price: '#881337',
      coverPlaceholderFrom: '#FDA4AF',
      coverPlaceholderTo: '#E11D48',
      coverScrim: 'linear-gradient(to top, rgba(136, 19, 55, 0.4), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.95)',
      floatButtonText: '#881337',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FFE4E6',
      productThumbBg: '#FFE4E6',
    }),
  },
  {
    id: 'trattoria-roma',
    name: 'Trattoria Roma',
    label: 'Trattoria',
    description:
      'Elegancia italiana con serif editorial, rosa romántico y acentos dorados.',
    bestFor: ['Trattoria', 'Pastas', 'Vino y cocina italiana'],
    context:
      'Elegancia italiana con serif Playfair, rosa romántico y acentos dorados. Sensación de trattoria europea íntima, con luz cálida y ambiente de cena especial.',
    recommendation:
      'Trattorias, pastelerías italianas, restaurantes de pasta fresca, vinos por copa y menús con risottos, carpaccios, lasañas y postres tiramisú.',
    designSystemQuery: 'italian trattoria elegant classic',
    typography: {
      headingFont: '"Playfair Display", Georgia, serif',
      bodyFont: 'Inter, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Playfair+Display:wght@400;500;600;700&display=swap',
      mood: 'elegant, luxury, sophisticated, timeless',
    },
    style: {
      name: 'Liquid Glass',
      keywords: ['premium', 'fluid', 'editorial', 'romantic'],
      borderRadius: 'rounded',
      cardRadiusPx: 14,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#DB2777',
      secondary: '#F472B6',
      accent: '#CA8A04',
      background: '#FDF2F8',
      surface: '#FFFFFF',
      text: '#831843',
      textMuted: '#9D174D',
      textSecondary: '#BE185D',
      border: '#FBCFE8',
      categoryActive: '#831843',
      categoryIndicator: '#DB2777',
      price: '#831843',
      coverPlaceholderFrom: '#F9A8D4',
      coverPlaceholderTo: '#DB2777',
      coverScrim: 'linear-gradient(to top, rgba(131, 24, 67, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.9)',
      floatButtonText: '#831843',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FCE7F3',
      productThumbBg: '#FCE7F3',
    }),
  },
  {
    id: 'sushi-zen',
    name: 'Sushi Zen',
    label: 'Sushi',
    description:
      'Minimalismo japonés: mucho blanco, negro profundo y acento dorado discreto.',
    bestFor: ['Sushi bar', 'Ramen', 'Cocina japonesa'],
    context:
      'Minimalismo japonés extremo: blanco puro, negro profundo y acento dorado discreto. Mucho espacio en blanco, tipografía Noto JP — calma, precisión y respeto al producto.',
    recommendation:
      'Sushi bars, omakase, restaurantes de cocina japonesa premium, menús con nigiri, sashimi, rolls especiales y sake. Funciona cuando las fotos del pescado son protagonistas.',
    designSystemQuery: 'japanese sushi minimal zen',
    typography: {
      headingFont: '"Noto Serif JP", Georgia, serif',
      bodyFont: '"Noto Sans JP", system-ui, sans-serif',
      headingWeight: 500,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@300;400;500;700&family=Noto+Serif+JP:wght@400;500;600;700&display=swap',
      mood: 'japanese, elegant, traditional, minimal',
    },
    style: {
      name: 'Trust & Authority',
      keywords: ['minimal', 'whitespace', 'precise', 'calm'],
      borderRadius: 'sharp',
      cardRadiusPx: 8,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#171717',
      secondary: '#404040',
      accent: '#D4AF37',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#171717',
      textMuted: '#525252',
      textSecondary: '#737373',
      border: '#E5E5E5',
      categoryActive: '#171717',
      categoryIndicator: '#171717',
      price: '#171717',
      coverPlaceholderFrom: '#525252',
      coverPlaceholderTo: '#171717',
      coverScrim: 'linear-gradient(to top, rgba(23, 23, 23, 0.45), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#171717',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F5F5F5',
      productThumbBg: '#F5F5F5',
    }),
  },
  {
    id: 'cafe-artesanal',
    name: 'Café Artesanal',
    label: 'Café',
    description:
      'Marrón café, crema cálida y tipografía handmade para coffee shops y panaderías de barrio.',
    bestFor: ['Cafetería', 'Brunch', 'Panadería de especialidad'],
    context:
      'Tonos café, crema y ámbar con tipografía handmade Amatic SC. Ambiente acogedor de barrio, artesanal y lento — como una cafetería de especialidad con pan recién horneado.',
    recommendation:
      'Cafeterías de especialidad, panaderías artesanales, brunch de fin de semana, menús con espresso, matcha, croissants, avo toast y repostería de mostrador.',
    designSystemQuery: 'coffee cafe artisan cozy',
    typography: {
      headingFont: '"Amatic SC", cursive',
      bodyFont: 'Cabin, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Amatic+SC:wght@400;700&family=Cabin:wght@400;500;600;700&display=swap',
      mood: 'indie, craft, artisan, organic',
    },
    style: {
      name: 'Exaggerated Minimalism',
      keywords: ['oversized type', 'warm', 'craft', 'cozy'],
      borderRadius: 'soft',
      cardRadiusPx: 16,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#78350F',
      secondary: '#92400E',
      accent: '#FBBF24',
      background: '#FEF3C7',
      surface: '#FFFBEB',
      text: '#451A03',
      textMuted: '#78350F',
      textSecondary: '#92400E',
      border: '#FDE68A',
      categoryActive: '#451A03',
      categoryIndicator: '#78350F',
      price: '#451A03',
      coverPlaceholderFrom: '#D97706',
      coverPlaceholderTo: '#78350F',
      coverScrim: 'linear-gradient(to top, rgba(69, 26, 3, 0.38), transparent)',
      floatButtonBg: 'rgba(255, 251, 235, 0.95)',
      floatButtonText: '#451A03',
      logoBorder: '#FFFBEB',
      logoPlaceholderBg: '#FEF3C7',
      productThumbBg: '#FEF3C7',
    }),
  },
  {
    id: 'burger-bold',
    name: 'Burger Bold',
    label: 'Burger',
    description:
      'Tipografía contundente y rojo apetitoso para fast food, burgers y wings.',
    bestFor: ['Hamburguesas', 'Fast food', 'Alitas y comfort food'],
    context:
      'Tipografía contundente Russo One/Chakra Petch con rojo apetitoso y bloques de alto contraste. Energía de fast food americano, directo y con hambre.',
    recommendation:
      'Hamburgueserías gourmet o clásicas, wings, hot dogs, comfort food americano, menús con combos, papas, malteadas y promos 2x1.',
    designSystemQuery: 'burger fast food bold energetic',
    typography: {
      headingFont: '"Russo One", system-ui, sans-serif',
      bodyFont: '"Chakra Petch", system-ui, sans-serif',
      headingWeight: 400,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Chakra+Petch:wght@300;400;500;600;700&family=Russo+One&display=swap',
      mood: 'bold, action, energetic, competitive',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['bold', 'block layout', 'high contrast', 'energetic'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#DC2626',
      secondary: '#F87171',
      accent: '#CA8A04',
      background: '#FEF2F2',
      surface: '#FFFFFF',
      text: '#450A0A',
      textMuted: '#7F1D1D',
      textSecondary: '#991B1B',
      border: '#FECACA',
      categoryActive: '#450A0A',
      categoryIndicator: '#DC2626',
      price: '#B45309',
      coverPlaceholderFrom: '#F87171',
      coverPlaceholderTo: '#B91C1C',
      coverScrim: 'linear-gradient(to top, rgba(69, 10, 10, 0.42), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#450A0A',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FEE2E2',
      productThumbBg: '#FEE2E2',
    }),
  },
  {
    id: 'ensalada-fresca',
    name: 'Ensalada Fresca',
    label: 'Saludable',
    description:
      'Verdes orgánicos y cyan fresco para bowls, ensaladas y cocina consciente.',
    bestFor: ['Ensaladas', 'Bowls', 'Vegan-friendly', 'Smoothies'],
    context:
      'Verdes orgánicos y cyan fresco con formas redondeadas y tipografía Lora/Raleway. Sensación wellness, ligereza y naturaleza — como un bowl bar de moda.',
    recommendation:
      'Ensaladerías, bowl bars, menús vegan-friendly, smoothies, jugos cold-pressed, poke saludable y opciones bajas en calorías o plant-based.',
    designSystemQuery: 'healthy salad organic fresh',
    typography: {
      headingFont: 'Lora, Georgia, serif',
      bodyFont: 'Raleway, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&family=Raleway:wght@300;400;500;600;700&display=swap',
      mood: 'calm, wellness, natural, organic',
    },
    style: {
      name: 'Organic Biophilic',
      keywords: ['nature', 'rounded', 'flowing', 'wellness'],
      borderRadius: 'pill',
      cardRadiusPx: 20,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#0891B2',
      secondary: '#22D3EE',
      accent: '#22C55E',
      background: '#ECFEFF',
      surface: '#FFFFFF',
      text: '#164E63',
      textMuted: '#155E75',
      textSecondary: '#0E7490',
      border: '#A5F3FC',
      categoryActive: '#164E63',
      categoryIndicator: '#0891B2',
      price: '#15803D',
      coverPlaceholderFrom: '#67E8F9',
      coverPlaceholderTo: '#0891B2',
      coverScrim: 'linear-gradient(to top, rgba(22, 78, 99, 0.32), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#164E63',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#CFFAFE',
      productThumbBg: '#CFFAFE',
    }),
  },
  {
    id: 'fine-dining-oro',
    name: 'Fine Dining Oro',
    label: 'Fine dining',
    description:
      'Piedra oscura, superficies claras y oro premium para alta cocina y cenas especiales.',
    bestFor: ['Fine dining', 'Chef table', 'Cocina de autor'],
    context:
      'Piedra oscura, superficies claras y acentos oro premium con serif Playfair. Estética de alta cocina editorial — sofisticado, reservado y con precios que se sienten especiales.',
    recommendation:
      'Fine dining, chef table, cocina de autor, menús degustación, maridajes y restaurantes donde el ticket promedio es alto y la experiencia es el producto.',
    designSystemQuery: 'fine dining luxury dark elegant',
    typography: {
      headingFont: '"Playfair Display", Georgia, serif',
      bodyFont: 'Inter, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700&family=Playfair+Display:wght@400;500;600;700&display=swap',
      mood: 'luxury, sophisticated, premium, editorial',
    },
    style: {
      name: 'Liquid Glass',
      keywords: ['luxury', 'premium', 'refined', 'editorial'],
      borderRadius: 'rounded',
      cardRadiusPx: 10,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#1C1917',
      secondary: '#44403C',
      accent: '#CA8A04',
      background: '#FAFAF9',
      surface: '#FFFFFF',
      text: '#0C0A09',
      textMuted: '#44403C',
      textSecondary: '#57534E',
      border: '#E7E5E4',
      categoryActive: '#0C0A09',
      categoryIndicator: '#CA8A04',
      price: '#0C0A09',
      priceSale: '#CA8A04',
      discountBadgeBg: '#F5F5F4',
      discountBadgeText: '#92400E',
      coverPlaceholderFrom: '#78716C',
      coverPlaceholderTo: '#1C1917',
      coverScrim: 'linear-gradient(to top, rgba(12, 10, 9, 0.5), transparent)',
      floatButtonBg: 'rgba(250, 250, 249, 0.92)',
      floatButtonText: '#0C0A09',
      logoBorder: '#FAFAF9',
      logoPlaceholderBg: '#F5F5F4',
      productThumbBg: '#F5F5F4',
    }),
  },
  {
    id: 'street-neon',
    name: 'Street Neon',
    label: 'Street food',
    description:
      'Modo oscuro con acentos neón púrpura y rosa — ideal para street food nocturno y bares.',
    bestFor: ['Street food', 'Night market', 'Bar snacks'],
    context:
      'Modo oscuro con acentos neón púrpura y rosa sobre fondo casi negro. Estética urbana nocturna, Bebas Neue condensada — mercado de noche o bar de snacks.',
    recommendation:
      'Street food nocturno, night markets, bares de botanas, menús con tacos al pastor de madrugada, wings, nachos y bebidas de bar.',
    designSystemQuery: 'street food urban neon',
    typography: {
      headingFont: '"Bebas Neue", system-ui, sans-serif',
      bodyFont: 'Karla, system-ui, sans-serif',
      headingWeight: 400,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Karla:wght@300;400;500;600;700&display=swap',
      mood: 'urban, nightlife, bold, contemporary',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['neon', 'dark', 'high contrast', 'urban'],
      borderRadius: 'sharp',
      cardRadiusPx: 10,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#A78BFA',
      secondary: '#7C3AED',
      accent: '#F43F5E',
      background: '#0F0F23',
      surface: '#1A1A2E',
      text: '#F1F5F9',
      textMuted: '#CBD5E1',
      textSecondary: '#94A3B8',
      border: '#312E81',
      categoryActive: '#F8FAFC',
      categoryIndicator: '#F43F5E',
      price: '#FDE68A',
      priceOriginal: '#94A3B8',
      priceSale: '#FB7185',
      discountBadgeBg: '#312E81',
      discountBadgeText: '#FDE68A',
      coverPlaceholderFrom: '#4C1D95',
      coverPlaceholderTo: '#0F0F23',
      coverScrim: 'linear-gradient(to top, rgba(15, 15, 35, 0.65), transparent)',
      floatButtonBg: 'rgba(26, 26, 46, 0.92)',
      floatButtonText: '#F1F5F9',
      logoBorder: '#1A1A2E',
      logoPlaceholderBg: '#312E81',
      productThumbBg: '#1E1B4B',
    }),
  },
  {
    id: 'mariscos-costa',
    name: 'Mariscos Costa',
    label: 'Mariscos',
    description:
      'Verde océano y azul costero con serif gastronómico para mariscos y cevicherías.',
    bestFor: ['Mariscos', 'Cevichería', 'Pescadería restaurante'],
    context:
      'Verde océano y azul costero con serif gastronómico Playfair SC. Frescura marina, brisa de playa y elegancia costera sin ser informal.',
    recommendation:
      'Marisquerías, cevicherías, pescaderías-restaurante, menús con aguachile, cóctel de camarón, pescado zarandeado y micheladas.',
    designSystemQuery: 'seafood coastal restaurant ocean',
    typography: {
      headingFont: '"Playfair Display SC", Georgia, serif',
      bodyFont: 'Karla, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Karla:wght@300;400;500;600;700&family=Playfair+Display+SC:wght@400;700&display=swap',
      mood: 'culinary, coastal, fresh, hospitality',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['fresh', 'coastal', 'ocean', 'natural'],
      borderRadius: 'rounded',
      cardRadiusPx: 14,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#059669',
      secondary: '#10B981',
      accent: '#0891B2',
      background: '#ECFDF5',
      surface: '#FFFFFF',
      text: '#064E3B',
      textMuted: '#047857',
      textSecondary: '#059669',
      border: '#A7F3D0',
      categoryActive: '#064E3B',
      categoryIndicator: '#059669',
      price: '#0E7490',
      coverPlaceholderFrom: '#34D399',
      coverPlaceholderTo: '#059669',
      coverScrim: 'linear-gradient(to top, rgba(6, 78, 59, 0.35), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.93)',
      floatButtonText: '#064E3B',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#D1FAE5',
      productThumbBg: '#D1FAE5',
    }),
  },
  {
    id: 'pizzeria-napoli',
    name: 'Pizzería Napoli',
    label: 'Pizza',
    description:
      'Rojo tomate, verde albahaca y crema — paleta clásica napolitana (ajustada para legibilidad).',
    bestFor: ['Pizzería', 'Calzones', 'Comida italiana casual'],
    context:
      'Rojo tomate, verde albahaca y crema cálida con Cormorant Garamond. Clásico napolitano artesanal — horno de leña, harina y mozzarella.',
    recommendation:
      'Pizzerías artesanales, calzones, focaccias, menús italianos casuales con pastas simples, bruschettas y vino de mesa.',
    designSystemQuery: 'pizzeria italian restaurant warm classic',
    typography: {
      headingFont: '"Cormorant Garamond", Georgia, serif',
      bodyFont: '"Source Sans 3", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Cormorant+Garamond:wght@500;600;700&family=Source+Sans+3:wght@300;400;500;600;700&display=swap',
      mood: 'classic, warm, mediterranean, artisan',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['classic', 'mediterranean', 'warm', 'artisan'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#B91C1C',
      secondary: '#15803D',
      accent: '#CA8A04',
      background: '#FFFBF5',
      surface: '#FFFFFF',
      text: '#1C1917',
      textMuted: '#44403C',
      textSecondary: '#57534E',
      border: '#FECACA',
      categoryActive: '#1C1917',
      categoryIndicator: '#B91C1C',
      price: '#15803D',
      coverPlaceholderFrom: '#FCA5A5',
      coverPlaceholderTo: '#B91C1C',
      coverScrim: 'linear-gradient(to top, rgba(28, 25, 23, 0.35), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#1C1917',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FEE2E2',
      productThumbBg: '#F5F5F4',
    }),
  },
  {
    id: 'pasteleria-dulce',
    name: 'Pastelería Dulce',
    label: 'Pastelería',
    description:
      'Pasteles suaves, tipografía redondeada y tonos miel-rosa para repostería y postres.',
    bestFor: ['Pastelería', 'Repostería', 'Heladería', 'Postres'],
    context:
      'Pasteles suaves rosa y miel con tipografía Pacifico redondeada. Dulce, invitador y con sensación de vitrina de postres — casi puedes oler el azúcar.',
    recommendation:
      'Pastelerías, reposterías finas, heladerías artesanales, menús con pasteles, cupcakes, macarons, cafés con postre y pan dulce.',
    designSystemQuery: 'bakery dessert pastel sweet',
    typography: {
      headingFont: 'Pacifico, cursive',
      bodyFont: 'Quicksand, system-ui, sans-serif',
      headingWeight: 400,
      bodyWeight: 500,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Pacifico&family=Quicksand:wght@400;500;600;700&display=swap',
      mood: 'sweet, playful, soft, inviting',
    },
    style: {
      name: 'Organic Biophilic',
      keywords: ['soft', 'pastel', 'rounded', 'sweet'],
      borderRadius: 'pill',
      cardRadiusPx: 18,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#DB2777',
      secondary: '#F472B6',
      accent: '#92400E',
      background: '#FFF7ED',
      surface: '#FFFFFF',
      text: '#78350F',
      textMuted: '#92400E',
      textSecondary: '#B45309',
      border: '#FBCFE8',
      categoryActive: '#78350F',
      categoryIndicator: '#DB2777',
      price: '#92400E',
      coverPlaceholderFrom: '#FBCFE8',
      coverPlaceholderTo: '#F472B6',
      coverScrim: 'linear-gradient(to top, rgba(120, 53, 15, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.94)',
      floatButtonText: '#78350F',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#FFEDD5',
      productThumbBg: '#FFEDD5',
    }),
  },
  ...EXTENDED_DIGITAL_MENU_THEMES,
  ...EXTENDED_DIGITAL_MENU_THEMES_2,
  ...DARK_DIGITAL_MENU_THEMES,
  ...FESTIVIDADES_MX_THEMES,
  ...VENUE_CATEGORY_DIGITAL_MENU_THEMES,
];

export const DEFAULT_DIGITAL_MENU_THEME_ID = 'original';
