import type { DigitalMenuTheme, DigitalMenuThemeColors } from './types';

function c(
  colors: Omit<
    DigitalMenuThemeColors,
    'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
  > &
    Partial<
      Pick<
        DigitalMenuThemeColors,
        'priceOriginal' | 'priceSale' | 'discountBadgeBg' | 'discountBadgeText'
      >
    >,
): DigitalMenuThemeColors {
  return {
    ...colors,
    priceOriginal: colors.priceOriginal ?? colors.textSecondary,
    priceSale: colors.priceSale ?? colors.primary,
    discountBadgeBg: colors.discountBadgeBg ?? colors.background,
    discountBadgeText: colors.discountBadgeText ?? colors.primary,
  };
}

/**
 * Essentials expansion — pure white canvas (background + surface #FFFFFF),
 * Original-like chrome; only accents and typography change (ui-ux-pro-max).
 */
export const ESSENTIALS_DIGITAL_MENU_THEMES: DigitalMenuTheme[] = [

  {
    id: 'white-crimson',
    name: 'White Crimson',
    label: 'Crimson',
    description: 'Lienzo blanco puro con rojo apetitoso. Solo cambia el acento.',
    bestFor: ['Cualquier restaurante', 'Comida casera', 'Delivery'],
    context:
      'Igual que Original en fondo y superficies blancas; acento crimson #DC2626 y Plus Jakarta Sans. Apetitoso sin teñir la página.',
    recommendation:
      'Cuando quieres el look limpio del Original con un acento rojo clásico de restaurante.',
    designSystemQuery: 'restaurant red accent white canvas plus jakarta',
    typography: {
      headingFont: '"Plus Jakarta Sans", system-ui, sans-serif',
      bodyFont: '"Plus Jakarta Sans", system-ui, sans-serif',
      headingWeight: 800,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400&display=swap',
      mood: 'clean, professional, appetizing, white canvas',
    },
    style: {
      name: 'Minimal default',
      keywords: ['white', 'crimson', 'clean', 'accent only'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#DC2626',
      secondary: '#F87171',
      accent: '#DC2626',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#DC2626',
      categoryIndicator: '#DC2626',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#DC2626',
      discountBadgeBg: '#FEF2F2',
      discountBadgeText: '#DC2626',
      coverPlaceholderFrom: '#FCA5A5',
      coverPlaceholderTo: '#DC2626',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-violet',
    name: 'White Violet',
    label: 'Violet',
    description: 'Blanco puro + violeta moderno con Nunito Black redondeada.',
    bestFor: ['Cualquier restaurante', 'Marcas young', 'Delivery'],
    context:
      'Canvas blanco Original; violeta #7C3AED y Nunito 900 soft-bold. Personalidad sin teñir fondos.',
    recommendation:
      'Marcas contemporáneas que quieren un acento distintivo sobre el mismo blanco limpio.',
    designSystemQuery: 'violet soft bold nunito white canvas essentials',
    typography: {
      headingFont: 'Nunito, system-ui, sans-serif',
      bodyFont: '"DM Sans", system-ui, sans-serif',
      headingWeight: 900,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400&family=Nunito:ital,wght@0,700;0,800;0,900;1,700&display=swap',
      mood: 'soft, bold, violet, white canvas',
    },
    style: {
      name: 'Exaggerated Minimalism',
      keywords: ['white', 'violet', 'soft bold', 'clean'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#7C3AED',
      secondary: '#A78BFA',
      accent: '#8B5CF6',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#7C3AED',
      categoryIndicator: '#7C3AED',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#7C3AED',
      discountBadgeBg: '#F5F3FF',
      discountBadgeText: '#6D28D9',
      coverPlaceholderFrom: '#C4B5FD',
      coverPlaceholderTo: '#7C3AED',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-navy',
    name: 'White Navy',
    label: 'Navy',
    description: 'Blanco puro + navy confiable con Outfit geométrico.',
    bestFor: ['Cualquier restaurante', 'Delivery', 'Cadenas'],
    context:
      'Lienzo blanco; navy #1E40AF y Outfit/Work Sans. Confianza tipo app de pedidos sin fondos tintados.',
    recommendation:
      'Restaurantes o dark kitchens que priorizan claridad y un azul serio sobre blanco.',
    designSystemQuery: 'navy trust outfit white canvas digital menu',
    typography: {
      headingFont: 'Outfit, system-ui, sans-serif',
      bodyFont: '"Work Sans", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=Work+Sans:wght@300;400;500;600;700&display=swap',
      mood: 'trust, navy, geometric, clean',
    },
    style: {
      name: 'Minimalism',
      keywords: ['white', 'navy', 'trust', 'clean'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#1E40AF',
      secondary: '#60A5FA',
      accent: '#2563EB',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#1E40AF',
      categoryIndicator: '#2563EB',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#1E40AF',
      discountBadgeBg: '#EFF6FF',
      discountBadgeText: '#1D4ED8',
      coverPlaceholderFrom: '#93C5FD',
      coverPlaceholderTo: '#1E40AF',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-emerald',
    name: 'White Emerald',
    label: 'Emerald',
    description: 'Blanco puro + esmeralda fresca. Como Original Verde, con tipografía propia.',
    bestFor: ['Cualquier restaurante', 'Fresh', 'Delivery'],
    context:
      'Canvas blanco; emerald #059669 y Poppins. Fresco y limpio — el verde vive solo en acentos.',
    recommendation:
      'Quien quiere el feel delivery-green sobre el mismo blanco del Original, con tipografía más definida.',
    designSystemQuery: 'emerald green poppins white canvas essentials',
    typography: {
      headingFont: 'Poppins, system-ui, sans-serif',
      bodyFont: '"Open Sans", system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400;500;600;700&family=Poppins:wght@400;500;600;700&display=swap',
      mood: 'fresh, clean, emerald, professional',
    },
    style: {
      name: 'Minimal default',
      keywords: ['white', 'emerald', 'fresh', 'clean'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#059669',
      secondary: '#34D399',
      accent: '#10B981',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#059669',
      categoryIndicator: '#10B981',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#059669',
      discountBadgeBg: '#ECFDF5',
      discountBadgeText: '#047857',
      coverPlaceholderFrom: '#6EE7B7',
      coverPlaceholderTo: '#059669',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-fuchsia',
    name: 'White Fuchsia',
    label: 'Fuchsia',
    description: 'Blanco puro + fucsia con Fredoka soft. Alegre sin teñir el fondo.',
    bestFor: ['Cualquier restaurante', 'Casual', 'Marcas young'],
    context:
      'Canvas blanco; fucsia #DB2777 y Fredoka/Nunito. Soft-bold juguetón solo en tipografía y acentos.',
    recommendation:
      'Marcas con tono divertido que aun así quieren el menú sobre blanco limpio.',
    designSystemQuery: 'fuchsia fredoka soft bold white canvas',
    typography: {
      headingFont: 'Fredoka, system-ui, sans-serif',
      bodyFont: 'Nunito, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Fredoka:wght@400;500;600;700&family=Nunito:wght@300;400;500;600;700&display=swap',
      mood: 'playful, soft, fuchsia, white canvas',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['white', 'fuchsia', 'soft', 'playful'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#DB2777',
      secondary: '#F472B6',
      accent: '#EC4899',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#DB2777',
      categoryIndicator: '#EC4899',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#DB2777',
      discountBadgeBg: '#FDF2F8',
      discountBadgeText: '#BE185D',
      coverPlaceholderFrom: '#F9A8D4',
      coverPlaceholderTo: '#DB2777',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-amber',
    name: 'White Amber',
    label: 'Amber',
    description: 'Blanco puro + ámbar apetitoso con Varela Round.',
    bestFor: ['Cualquier restaurante', 'Delivery', 'Fast casual'],
    context:
      'Canvas blanco; ámbar #D97706 y Varela Round/Nunito Sans. Apetito en el acento, no en el fondo.',
    recommendation:
      'Menús delivery/fast casual que quieren naranja-ámbar sobre el mismo blanco del Original.',
    designSystemQuery: 'amber food delivery white canvas varela round',
    typography: {
      headingFont: '"Varela Round", system-ui, sans-serif',
      bodyFont: '"Nunito Sans", system-ui, sans-serif',
      headingWeight: 400,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Nunito+Sans:wght@300;400;500;600;700&family=Varela+Round&display=swap',
      mood: 'soft, appetizing, amber, white canvas',
    },
    style: {
      name: 'Minimal default',
      keywords: ['white', 'amber', 'soft', 'appetite'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#D97706',
      secondary: '#FBBF24',
      accent: '#F59E0B',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#D97706',
      categoryIndicator: '#F59E0B',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#D97706',
      discountBadgeBg: '#FFFBEB',
      discountBadgeText: '#B45309',
      coverPlaceholderFrom: '#FCD34D',
      coverPlaceholderTo: '#D97706',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-cyan',
    name: 'White Cyan',
    label: 'Cyan',
    description: 'Blanco puro + cian fresco con Baloo 2 soft.',
    bestFor: ['Cualquier restaurante', 'Familiar', 'Pedidos móviles'],
    context:
      'Canvas blanco; cian #0891B2 y Baloo 2/Quicksand. Fresco y soft sin teñir superficies.',
    recommendation:
      'Marcas claras y positivas que quieren un acento frío sobre blanco total.',
    designSystemQuery: 'cyan soft baloo white canvas essentials',
    typography: {
      headingFont: '"Baloo 2", system-ui, sans-serif',
      bodyFont: 'Quicksand, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 500,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Baloo+2:wght@400;500;600;700&family=Quicksand:wght@400;500;600;700&display=swap',
      mood: 'soft, cyan, friendly, white canvas',
    },
    style: {
      name: 'Exaggerated Minimalism',
      keywords: ['white', 'cyan', 'soft', 'fresh'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#0891B2',
      secondary: '#22D3EE',
      accent: '#06B6D4',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#0891B2',
      categoryIndicator: '#06B6D4',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#0891B2',
      discountBadgeBg: '#ECFEFF',
      discountBadgeText: '#0E7490',
      coverPlaceholderFrom: '#67E8F9',
      coverPlaceholderTo: '#0891B2',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-royal',
    name: 'White Royal',
    label: 'Royal',
    description: 'Blanco puro + índigo royal con Plus Jakarta.',
    bestFor: ['Cualquier restaurante', 'Premium casual', 'Marca moderna'],
    context:
      'Canvas blanco; royal indigo #4338CA y Plus Jakarta ExtraBold. Sofisticado y limpio.',
    recommendation:
      'Marcas modernas que quieren un acento frío elegante sin fondos de color.',
    designSystemQuery: 'royal indigo plus jakarta white canvas',
    typography: {
      headingFont: '"Plus Jakarta Sans", system-ui, sans-serif',
      bodyFont: '"Plus Jakarta Sans", system-ui, sans-serif',
      headingWeight: 800,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:ital,wght@0,400;0,500;0,600;0,700;0,800;1,400&display=swap',
      mood: 'modern, royal, clean, professional',
    },
    style: {
      name: 'Minimalism',
      keywords: ['white', 'royal', 'indigo', 'clean'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#4338CA',
      secondary: '#818CF8',
      accent: '#4F46E5',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#4338CA',
      categoryIndicator: '#4F46E5',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#4338CA',
      discountBadgeBg: '#EEF2FF',
      discountBadgeText: '#3730A3',
      coverPlaceholderFrom: '#A5B4FC',
      coverPlaceholderTo: '#4338CA',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-wine',
    name: 'White Wine',
    label: 'Wine',
    description: 'Blanco puro + vino editorial con Playfair.',
    bestFor: ['Cualquier restaurante', 'Hospitality', 'Menú con carácter'],
    context:
      'Canvas blanco; wine #9F1239 y Playfair/Karla. Editorial gastronómico sin fondo tintado.',
    recommendation:
      'Quien quiere elegancia de carta sobre el mismo blanco limpio del Original.',
    designSystemQuery: 'wine editorial playfair white canvas restaurant',
    typography: {
      headingFont: '"Playfair Display", Georgia, serif',
      bodyFont: 'Karla, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Karla:wght@300;400;500;600;700&family=Playfair+Display:wght@400;500;600;700&display=swap',
      mood: 'editorial, wine, elegant, white canvas',
    },
    style: {
      name: 'Liquid Glass',
      keywords: ['white', 'wine', 'editorial', 'serif'],
      borderRadius: 'rounded',
      cardRadiusPx: 10,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#9F1239',
      secondary: '#FB7185',
      accent: '#BE123C',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#9F1239',
      categoryIndicator: '#BE123C',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#9F1239',
      discountBadgeBg: '#FFF1F2',
      discountBadgeText: '#9F1239',
      coverPlaceholderFrom: '#FDA4AF',
      coverPlaceholderTo: '#9F1239',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-olive',
    name: 'White Olive',
    label: 'Olive',
    description: 'Blanco puro + oliva natural con Manrope.',
    bestFor: ['Cualquier restaurante', 'Fresh', 'Casual'],
    context:
      'Canvas blanco; oliva #4D7C0F y Manrope/Source Sans. Natural y contemporáneo, sin teñir la página.',
    recommendation:
      'Marcas con tono natural/vegetal que quieren acento oliva sobre blanco total.',
    designSystemQuery: 'olive green manrope white canvas essentials',
    typography: {
      headingFont: 'Manrope, system-ui, sans-serif',
      bodyFont: '"Source Sans 3", system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&family=Source+Sans+3:wght@300;400;500;600;700&display=swap',
      mood: 'natural, olive, modern, white canvas',
    },
    style: {
      name: 'Minimalism',
      keywords: ['white', 'olive', 'natural', 'clean'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#4D7C0F',
      secondary: '#A3E635',
      accent: '#65A30D',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#4D7C0F',
      categoryIndicator: '#65A30D',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#4D7C0F',
      discountBadgeBg: '#F7FEE7',
      discountBadgeText: '#3F6212',
      coverPlaceholderFrom: '#BEF264',
      coverPlaceholderTo: '#4D7C0F',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-sunset',
    name: 'White Sunset',
    label: 'Sunset',
    description: 'Blanco puro + coral atardecer con Nunito Black.',
    bestFor: ['Cualquier restaurante', 'Delivery', 'Casual'],
    context:
      'Canvas blanco; sunset coral #F43F5E y Nunito 900. Soft-bold tipo pedido moderno, fondo blanco intacto.',
    recommendation:
      'Marcas amigables que quieren el look “Start an Order” con acento coral sobre blanco puro.',
    designSystemQuery: 'sunset coral nunito black white canvas order',
    typography: {
      headingFont: 'Nunito, system-ui, sans-serif',
      bodyFont: '"DM Sans", system-ui, sans-serif',
      headingWeight: 900,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400&family=Nunito:ital,wght@0,700;0,800;0,900;1,700&display=swap',
      mood: 'soft bold, sunset, friendly, white canvas',
    },
    style: {
      name: 'Exaggerated Minimalism',
      keywords: ['white', 'sunset', 'soft bold', 'coral'],
      borderRadius: 'soft',
      cardRadiusPx: 16,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#F43F5E',
      secondary: '#FB7185',
      accent: '#FB923C',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#F43F5E',
      categoryIndicator: '#F43F5E',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#EA580C',
      discountBadgeBg: '#FFF1F2',
      discountBadgeText: '#E11D48',
      coverPlaceholderFrom: '#FDA4AF',
      coverPlaceholderTo: '#F43F5E',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-ocean',
    name: 'White Ocean',
    label: 'Ocean',
    description: 'Blanco puro + ocean teal con Outfit.',
    bestFor: ['Cualquier restaurante', 'Casual moderno', 'Delivery'],
    context:
      'Canvas blanco; ocean #0E7490 y Outfit. Teal confiable solo en acentos — superficies intactas.',
    recommendation:
      'Alternativa al verde delivery: teal océano sobre el mismo blanco limpio.',
    designSystemQuery: 'ocean teal outfit white canvas essentials',
    typography: {
      headingFont: 'Outfit, system-ui, sans-serif',
      bodyFont: '"Work Sans", system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;500;600;700&family=Work+Sans:wght@300;400;500;600;700&display=swap',
      mood: 'ocean, teal, clean, trust',
    },
    style: {
      name: 'Minimalism',
      keywords: ['white', 'ocean', 'teal', 'clean'],
      borderRadius: 'rounded',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#0E7490',
      secondary: '#22D3EE',
      accent: '#14B8A6',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#0E7490',
      categoryIndicator: '#14B8A6',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#0E7490',
      discountBadgeBg: '#F0FDFA',
      discountBadgeText: '#0F766E',
      coverPlaceholderFrom: '#5EEAD4',
      coverPlaceholderTo: '#0E7490',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-plum',
    name: 'White Plum',
    label: 'Plum',
    description: 'Blanco puro + ciruela con Lora editorial suave.',
    bestFor: ['Cualquier restaurante', 'Casual elegante', 'Hospitality'],
    context:
      'Canvas blanco; plum #6B21A8 y Lora/Raleway. Sofisticado y calmado — solo el acento aporta color.',
    recommendation:
      'Marcas con tono refinado que quieren un acento ciruela sin fondos tintados.',
    designSystemQuery: 'plum lora raleway white canvas essentials',
    typography: {
      headingFont: 'Lora, Georgia, serif',
      bodyFont: 'Raleway, system-ui, sans-serif',
      headingWeight: 600,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Lora:wght@400;500;600;700&family=Raleway:wght@300;400;500;600;700&display=swap',
      mood: 'elegant, plum, soft, white canvas',
    },
    style: {
      name: 'Organic Biophilic',
      keywords: ['white', 'plum', 'serif', 'refined'],
      borderRadius: 'soft',
      cardRadiusPx: 12,
      categoryTabStyle: 'underline',
    },
    colors: c({
      primary: '#6B21A8',
      secondary: '#C084FC',
      accent: '#7E22CE',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#6B21A8',
      categoryIndicator: '#7E22CE',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#6B21A8',
      discountBadgeBg: '#FAF5FF',
      discountBadgeText: '#6B21A8',
      coverPlaceholderFrom: '#D8B4FE',
      coverPlaceholderTo: '#6B21A8',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-impact',
    name: 'White Impact',
    label: 'Impact',
    description: 'Blanco puro + negro/rojo con Bebas Neue de impacto.',
    bestFor: ['Cualquier restaurante', 'Bold', 'Street casual'],
    context:
      'Canvas blanco; tipografía Bebas Neue de alto impacto y acento rojo #B91C1C. Titulares fuertes, página blanca.',
    recommendation:
      'Marcas bold que quieren headlines potentes sin abandonar el fondo blanco del Original.',
    designSystemQuery: 'bold bebas neue red accent white canvas menu',
    typography: {
      headingFont: '"Bebas Neue", system-ui, sans-serif',
      bodyFont: '"Source Sans 3", system-ui, sans-serif',
      headingWeight: 400,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=Bebas+Neue&family=Source+Sans+3:wght@300;400;500;600;700&display=swap',
      mood: 'bold, impactful, modern, white canvas',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['white', 'impact', 'bold', 'display'],
      borderRadius: 'sharp',
      cardRadiusPx: 10,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#111827',
      secondary: '#F87171',
      accent: '#B91C1C',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#FFFFFF',
      categoryIndicator: '#111827',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#B91C1C',
      discountBadgeBg: '#FEF2F2',
      discountBadgeText: '#B91C1C',
      coverPlaceholderFrom: '#CBD5E1',
      coverPlaceholderTo: '#64748B',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-graphite',
    name: 'White Graphite',
    label: 'Graphite+',
    description: 'Blanco puro + grafito y lima CTA. Alto contraste tipográfico.',
    bestFor: ['Cualquier restaurante', 'Urbano', 'Marcas bold'],
    context:
      'Canvas blanco; grafito #18181B y lima #65A30D solo en CTA/precios oferta. DM Sans + Inter contemporáneo.',
    recommendation:
      'Look urbano de alto contraste sin fondos grises ni tintados — solo blanco y acentos.',
    designSystemQuery: 'graphite lime dm sans white canvas high contrast',
    typography: {
      headingFont: '"DM Sans", system-ui, sans-serif',
      bodyFont: 'Inter, system-ui, sans-serif',
      headingWeight: 700,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400&family=Inter:wght@300;400;500;600;700&display=swap',
      mood: 'contemporary, contrast, white canvas',
    },
    style: {
      name: 'Vibrant & Block-based',
      keywords: ['white', 'graphite', 'lime', 'contrast'],
      borderRadius: 'sharp',
      cardRadiusPx: 10,
      categoryTabStyle: 'filled',
    },
    colors: c({
      primary: '#18181B',
      secondary: '#71717A',
      accent: '#65A30D',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#FFFFFF',
      categoryIndicator: '#18181B',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#65A30D',
      discountBadgeBg: '#F7FEE7',
      discountBadgeText: '#4D7C0F',
      coverPlaceholderFrom: '#A1A1AA',
      coverPlaceholderTo: '#3F3F46',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
  {
    id: 'white-blush',
    name: 'White Blush',
    label: 'Blush',
    description:
      'Lienzo blanco puro con acento blush pastel #F5BCCD. Suave, limpio y femenino.',
    bestFor: ['Cualquier restaurante', 'Marcas soft', 'Casual elegante'],
    context:
      'Canvas blanco como Original; acento principal exacto #F5BCCD (blush pastel). Tipografía Nunito soft-bold; el rosa vive solo en acentos, no en el fondo.',
    recommendation:
      'Marcas con tono suave o romantic que quieren el blanco limpio del Original con un accent blush preciso.',
    designSystemQuery: 'pastel blush pink #F5BCCD accent white canvas soft nunito',
    typography: {
      headingFont: 'Nunito, system-ui, sans-serif',
      bodyFont: '"DM Sans", system-ui, sans-serif',
      headingWeight: 800,
      bodyWeight: 400,
      googleFontsUrl:
        'https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,700;1,400&family=Nunito:ital,wght@0,700;0,800;0,900;1,700&display=swap',
      mood: 'soft, blush, pastel, white canvas, friendly',
    },
    style: {
      name: 'Exaggerated Minimalism',
      keywords: ['white', 'blush', 'pastel pink', 'soft', '#F5BCCD'],
      borderRadius: 'soft',
      cardRadiusPx: 14,
      categoryTabStyle: 'pill',
    },
    colors: c({
      primary: '#F5BCCD',
      secondary: '#FAD4E0',
      accent: '#F5BCCD',
      background: '#FFFFFF',
      surface: '#FFFFFF',
      text: '#111827',
      textMuted: '#64748B',
      textSecondary: '#94A3B8',
      border: '#EEF2F7',
      categoryActive: '#7A3A52',
      categoryIndicator: '#F5BCCD',
      price: '#111827',
      priceOriginal: '#94A3B8',
      priceSale: '#C45B7A',
      discountBadgeBg: '#FFF0F5',
      discountBadgeText: '#9F4D68',
      coverPlaceholderFrom: '#FAD4E0',
      coverPlaceholderTo: '#F5BCCD',
      coverScrim: 'linear-gradient(to top, rgba(15, 23, 42, 0.28), transparent)',
      floatButtonBg: 'rgba(255, 255, 255, 0.92)',
      floatButtonText: '#111827',
      logoBorder: '#FFFFFF',
      logoPlaceholderBg: '#F1F5F9',
      productThumbBg: '#F1F5F9',
    }),
  },
];
